upd

diff --git a/sbin/^template_with_getopt_no_head_foot b/sbin/^template_with_getopt_no_head_foot
--- a/sbin/^template_with_getopt_no_head_foot
+++ b/sbin/^template_with_getopt_no_head_foot
@@ -31,11 +31,39 @@
 ### FILL IN THESE VARIABLES!!! ###
      PURPOSE="SAMPLE PURPOSE" # Don't include $0, e.g., "Saves the world" 
      USAGE="SAMPLE USAGE" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
+          # SAMPLE below for two arguments
+          # USAGE="[-vh --help --version] <search-string> <filename>" 
+          # SAMPLE below for stream management
+          # USAGE="[-ifsvh --input --file --stream --help--version] <substring> [<source-string>]"
      VERSION_NUMBER="0.1"
-     COLOPHON="(c) $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
+     ROOT_REQUIRED=false
+     OPTIONS=(
+          "-i --input                                      Use standard input for input (default)"
+          "-f<source-file-name> --file=<source-file-name>  Use specified file contents for input"
+          "-s<source-string> --string=<source-string>      Use specified string for input"
+          "     IMPORTANT: The three lines above are mutually exclusive. Default is -i or --input."
+          "-q --quiet    Minimal output"
+          "-V --verbose  Verbose output"
+          "-v --version  Display version number, then exit (no other options processed)"
+          "-h --help     Display usage and help information, then exit (no other options processed)"
+          )
+     EXAMPLE_USAGE=(
+          "Example usages: cat <filename> | $(basename $0)"
+          "                echo \$string | $(basename $0)"
+          "                $(basename $0) <input-string>"
+          "                $(basename $0) "-s\<input-string\>""
+          "                $(basename $0) "-string=\<input-string\>""
+          "                $(basename $0) -f\<source-file-name\>"
+          "                $(basename $0) -file=\<source-file-name\>"
+          )
+     SHORT_GETOPT="hv"; LONG_GETOPT="help,version"
+     # Including quiet & verbose: SHORT_GETOPT="hqVv"; LONG_GETOPT="help,quiet,verbose,version"
+     # Including stream options: SHORT_GETOPT="if:s:hv"; LONG_GETOPT="input,file:,stream:,help,version"
+
 
 # Stable variables; OK to leave this in without edits.
      ARGS="" # Adapted when flags are parsed.
+     COLOPHON="$(printf "\u00A9") $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
      EXIT_CODE_SUCCESS=0
      EXIT_CODE_EPERM=1 # Operation not permitted
      EXIT_CODE_ENOENT=2 # No such file or directory
@@ -69,44 +97,31 @@
 ###################################################
 # Functions
 
-# EDIT THIS!
+# LEAVE THIS ALONE!
 function f_print_usage {
-  echo "$PROGRAM_NAME version $VERSION_NUMBER" >&2
+  printf "%s" "$PROGRAM_NAME $VERSION_NUMBER" >&2
+  if [ $# -gt 0 ] ; then echo ": Error: $1" ; else echo "" ; fi
+  echo $COLOPHON >&2
   echo Usage: $PROGRAM_NAME $USAGE >&2
   echo Purpose: $PURPOSE >&2
-  echo Requires root or sudo. >&2 #OPTIONAL!
-  echo >&2
+  if $ROOT_REQUIRED ; then echo Requires root or sudo. >&2 ; fi
   echo "Options:" >&2
-  echo "  -q --quiet                        Mimimal output" >&2
-  echo "  -V --verbose                      Verbose output" >&2
-  echo "  -v --version                      Display version number, then exit (no other options processed)" >&2
-  echo "  -h --help                         Display usage and help information, then exit (no other options processed)" >&2
-  echo >&2
-  echo "Example usage: " $PROGRAM_NAME >&2
-  echo >&2 ; echo $COLOPHON >&2
-}
-
-# OK as is; no need to update
-function f_alert () {
-	# Information for user.
-     # Variable 1: Error or other message (e.g., "File not found")
-     echo "$PROGRAM_NAME version $VERSION_NUMBER: $1" >&2
-	echo "Usage: $PROGRAM_NAME $USAGE" >&2
-     echo "Purpose: $PURPOSE" >&2
-     echo "$COLOPHON" >&2
-	}
+  for i in "${!OPTIONS[@]}"; do
+     echo "  ${OPTIONS[$i]}" >&2
+     done
+  for i in "${!EXAMPLE_USAGE[@]}"; do
+     echo "${EXAMPLE_USAGE[$i]}" >&2
+     done
+  }
 
 
 ###################################################
-# General error testing
+# Test for big problems
 
-# Review this.
-# CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
-if [ $# -ne 0 ]; 
-     then echo "Invalid number of arguments." >&2
-	f_print_usage
-	exit $EXIT_CODE_INVALID_ARGUMENTS
-fi
+if $ROOT_REQUIRED && [[ $EUID -ne 0 ]]; then
+     f_print_usage "Root privileges required."
+     exit EXIT_CODE_ROOT_REQUIRED
+     fi
 
 
 ###################################################
@@ -127,11 +142,12 @@ fi
 #       Similarly for long options, options optionA, optionB, and optionC are switches; optiona, optionb, and optionc expect arguments
 #   Double Colon after an option means an argument is optional. 
 #   The '-- "$@"' at the end means that all other command arguments are "remaining arguments".
-PARSED_ARGUMENTS=$(getopt --name $PROGRAM_NAME --options hqVv \
-    --long help,quiet,verbose,version \
-    -- "$@")
-VALID_ARGUMENTS=$?
-if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
+# For more info on getopt syntax: https://linux.die.net/man/1/getopt
+     PARSED_ARGUMENTS=$(getopt --name $PROGRAM_NAME --options $SHORT_GETOPT \
+          --long $LONG_GETOPT -- "$@")
+# Taking this out. Not sure what it does.
+     # VALID_ARGUMENTS=$?
+     #if [ "$VALID_ARGUMENTS" != "0" ] ; then f_print_usage ; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
 
 # Note about next command: 
 # By reading that set of standardised arguments into the shell's input arguments 
@@ -140,30 +156,45 @@ eval set -- "$PARSED_ARGUMENTS"
 
 while : ; do
     case "$1" in
-      -h | --help )  # Help, if you're so stupid that you don't get that :)
+#       -f | --file )
+#          MODE=file
+#          string=$(cat "$2")
+#          shift 2
+#           ;;   
+#       -s | --string )
+#          MODE=string
+#          string="$2"
+#          shift 2
+#           ;;   
+#       -i | --input ) # Doesn't do anything here because it's dealt with in default above.
+#          shift 1
+#           ;;   
+       -h | --help )  # Help, if you're so stupid that you don't get that :)
            f_print_usage
            exit $EXIT_CODE_SUCCESS
            ;;   
       -v | --version)  # Version number
-           echo $PROGRAM_NAME: version $VERSION_NUMBER >&2
+           echo $(basename $0): version $VERSION_NUMBER >&2
            exit $EXIT_CODE_SUCCESS
            ;;
-      -q | --quiet)  # Quiet mode
-           QUIET_MODE=true
-           REDIRECT="/dev/null"
-           ARGS+=" --quiet"
-           shift # Only one (default) shift for a switch, i.e., no argument
-           ;;
-      -V | --verbose)  # Verbose mode
-           VERBOSE_MODE=true
-           shift # Only one (default) shift for a switch, i.e., no argument
-           ;;
+#      -q | --quiet)  # Quiet mode
+#          ##### DROP THIS OPTION?
+#           QUIET_MODE=true
+#           REDIRECT="/dev/null"
+#           ARGS+=" --quiet"
+#           shift # Only one (default) shift for a switch, i.e., no argument
+#           ;;
+#      -V | --verbose)  # Verbose mode
+#          ##### DROP THIS OPTION?
+#           VERBOSE_MODE=true
+#           shift # Only one (default) shift for a switch, i.e., no argument
+#           ;;
       --) # -- means the end of the arguments; drop this, and break out of the while loop
            shift
            break 
            ;;
       *) # Invalid option.
-          f_alert "Invalid option."
+          f_print_usage "Invalid option."
           exit EXIT_CODE_INVALID_OPTIONS
            ;;
   esac
@@ -178,6 +209,13 @@ done
 #           Environment variables are fine for optional values.
 #   We haven't yet tested for the existence of required options and/or remaining arguments (now $1, $2, etc.)
 #   We also haven't yet tested for the valid options arguments and/or remaining arguments (now $1, $2, etc.)
+
+# EDIT this.
+# CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS, and add error message.
+if [ $# -ne 0 ] ; then
+	f_print_usage "Error message"
+	exit $EXIT_CODE_INVALID_ARGUMENTS
+     fi
 
 echo "I don't do anything yet." >&2
 
diff --git a/sbin/cursor b/sbin/cursor
--- a/sbin/cursor
+++ b/sbin/cursor
@@ -29,12 +29,13 @@
 # Basic Setup
 
 ### FILL IN THESE VARIABLES!!! ###
-     COLOPHON="(c) $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
+     COLOPHON="$(printf "\u00A9") $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
      PURPOSE="Displays the row or column cursor position, top left being 0 0" # Don't include $0, e.g., "Prints the first 5 characters of a string" 
      USAGE="[-crhv --column --row --help --version]" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
      VERSION_NUMBER="0.1"
      QUIET_MODE=false
      VERBOSE_MODE=false
+     ROOT_REQUIRED=false
 
 # Stable variables; OK to leave this in without edits.
      ARGS="" # Adapted when flags are parsed.
@@ -62,7 +63,8 @@
      EXIT_CODE_FILE_IN_USE=171
      EXIT_CODE_WRONG_HOST=172
      EXIT_CODE_INVALID_ARGUMENTS=173
-     PROGRAM_NAME=$(basename "$0")
+     PROGRAM_NAME="$(basename $0)"
+     QUIET_MODE=false
      REDIRECT="/dev/stdout" # Switch to "/dev/null" for quiet mode. This is where text that could be suppressed by quiet mode is directed. 
 
 ###################################################
@@ -70,37 +72,26 @@
 
 # EDIT THIS!
 function f_print_usage {
-  echo "$PROGRAM_NAME version $VERSION_NUMBER" >&2
+  printf "%s" "$PROGRAM_NAME $VERSION_NUMBER" >&2
+  if [ $# -gt 0 ] ; then echo ": Error: $1" >&2 ; else echo "" >&2 ; fi
+  echo $COLOPHON >&2
   echo Usage: $PROGRAM_NAME $USAGE >&2
   echo Purpose: $PURPOSE >&2
-#  echo Requires root or sudo. >&2 #OPTIONAL!
-  echo >&2
+  if $ROOT_REQUIRED ; then echo Requires root or sudo. >&2 ; fi
   echo "Options:" >&2
-#  echo "  -q --quiet                        Mimimal output" >&2
+#  echo "  -q --quiet                        Minimal output" >&2
 #  echo "  -V --verbose                      Verbose output" >&2
   echo "  -c --column   Display column (default, and overrides -r or --row if -c or --column selected)" >&2
   echo "  -r --row      Display row (works only if neither -c nor --column selected)" >&2
   echo "  -v --version  Display version number, then exit (no other options processed)" >&2
   echo "  -h --help     Display usage and help information, then exit (no other options processed)" >&2
-  echo >&2
   echo "Example usage: " $PROGRAM_NAME -c >&2
   echo "               " $PROGRAM_NAME --column >&2
   echo "               " $PROGRAM_NAME -r >&2
   echo "               " $PROGRAM_NAME --row >&2
   echo "               " $PROGRAM_NAME -c -r >&2
   echo "               " $PROGRAM_NAME --column --row >&2
-  echo >&2 ; echo $COLOPHON >&2
   }
-
-# OK as is; no need to update
-function f_alert () {
-	# Information for user.
-     # Variable 1: Error or other message (e.g., "File not found")
-     echo "$PROGRAM_NAME version $VERSION_NUMBER: $1" >&2
-     echo "$COLOPHON" >&2
-	echo "Usage: $PROGRAM_NAME $USAGE" >&2
-     echo "Purpose: $PURPOSE" >&2
-	}
 
 
 ###################################################
@@ -128,7 +119,7 @@ PARSED_ARGUMENTS=$(getopt --name $PROGRAM_NAME --options crhv \
     --long column,row,help,version \
     -- "$@")
 VALID_ARGUMENTS=$?
-if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
+if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage "Invalid arguments"; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
 
 # Note about next command: 
 # By reading that set of standardised arguments into the shell's input arguments 
@@ -184,7 +175,7 @@ while : ; do
            break 
            ;;
       *) # Invalid option.
-          f_alert "Invalid option."
+          f_print_usage "Invalid option."
           exit EXIT_CODE_INVALID_OPTIONS
            ;;
   esac
@@ -197,11 +188,10 @@ done
 
 # Review this.
 # CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
-if [ $# -ne 0 ]; 
-     then echo "Invalid number of arguments." >&2
-	f_print_usage
+if [ $# -ne 0 ] ; then
+	f_print_usage "Invalid number of arguments."
 	exit $EXIT_CODE_INVALID_ARGUMENTS
-fi
+     fi
 
 
 ###################################################
diff --git a/sbin/find-in-file b/sbin/find-in-file
--- a/sbin/find-in-file
+++ b/sbin/find-in-file
@@ -29,15 +29,24 @@
 # Basic Setup
 
 ### FILL IN THESE VARIABLES!!! ###
-     PURPOSE="Displays the first <number-of-characters> characters of a string." # Don't include $0, e.g., "Saves the world" 
-     USAGE="[-hv --help --version] <source-string> <number-of-characters>" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
+     PURPOSE="Finds the position of a search-string in a text-file" # Don't include $0, e.g., "Saves the world" 
+     USAGE="[-vh --help --version] <search-string> <filename>" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
      VERSION_NUMBER="0.1"
-     COLOPHON="$(printf "\u00A9") $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
      ROOT_REQUIRED=false
-     VERBOSE_MODE=false
+     OPTIONS=(
+          "-v --version  Display version number, then exit (no other options processed)"
+          "-h --help     Display usage and help information, then exit (no other options processed)"
+          )
+     EXAMPLE_USAGE=(
+          "Example usage: $(basename $0) <html> <index.html>"
+          "  Returns position of the search-string with exit code 0."
+          "  If not found, returns nothing with exit code 173."
+          )
+     SHORT_GETOPT="hv"; LONG_GETOPT="help,version"
 
 # Stable variables; OK to leave this in without edits.
      ARGS="" # Adapted when flags are parsed.
+     COLOPHON="$(printf "\u00A9") $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
      EXIT_CODE_SUCCESS=0
      EXIT_CODE_EPERM=1 # Operation not permitted
      EXIT_CODE_ENOENT=2 # No such file or directory
@@ -65,24 +74,37 @@
      PROGRAM_NAME="$(basename $0)"
      QUIET_MODE=false
      REDIRECT="/dev/stdout" # Switch to "/dev/null" for quiet mode. This is where text that could be suppressed by quiet mode is directed. 
+     VERBOSE_MODE=false
 
 
 ###################################################
 # Functions
 
-# EDIT THIS!
+# LEAVE THIS ALONE!
 function f_print_usage {
   printf "%s" "$PROGRAM_NAME $VERSION_NUMBER" >&2
-  if [ $# -gt 0 ] ; then echo ": Error: $1" >&2 ; else echo "" >&2 ; fi
+  if [ $# -gt 0 ] ; then echo ": Error: $1" ; else echo "" ; fi
   echo $COLOPHON >&2
   echo Usage: $PROGRAM_NAME $USAGE >&2
   echo Purpose: $PURPOSE >&2
   if $ROOT_REQUIRED ; then echo Requires root or sudo. >&2 ; fi
   echo "Options:" >&2
-  echo "  -v --version  Display version number, then exit (no other options processed)" >&2
-  echo "  -h --help     Display usage and help information, then exit (no other options processed)" >&2
-  echo "Example usage: " $PROGRAM_NAME supercalifragilisticexpialidocious 5 >&2
-}
+  for i in "${!OPTIONS[@]}"; do
+     echo "  ${OPTIONS[$i]}" >&2
+     done
+  for i in "${!EXAMPLE_USAGE[@]}"; do
+     echo "${EXAMPLE_USAGE[$i]}" >&2
+     done
+  }
+
+
+###################################################
+# Test for big problems
+
+if $ROOT_REQUIRED && [[ $EUID -ne 0 ]]; then
+     f_print_usage "Root privileges required."
+     exit EXIT_CODE_ROOT_REQUIRED
+     fi
 
 
 ###################################################
@@ -101,13 +123,14 @@ function f_print_usage {
 #   Colon after an option means an argument is required. 
 #       In this example, options A, B, and C are switches; a, b, and c expect arguments
 #       Similarly for long options, options optionA, optionB, and optionC are switches; optiona, optionb, and optionc expect arguments
-#   Double Colon after an option means an argument is optional.
+#   Double Colon after an option means an argument is optional. 
 #   The '-- "$@"' at the end means that all other command arguments are "remaining arguments".
-PARSED_ARGUMENTS=$(getopt --name $PROGRAM_NAME --options hv \
-    --long help,version \
-    -- "$@")
-VALID_ARGUMENTS=$?
-if [ "$VALID_ARGUMENTS" != "0" ] ; then f_print_usage "Invalid arguments" ; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
+# For more info on getopt syntax: https://linux.die.net/man/1/getopt
+     PARSED_ARGUMENTS=$(getopt --name $PROGRAM_NAME --options $SHORT_GETOPT \
+          --long $LONG_GETOPT -- "$@")
+# Taking this out. Not sure what it does.
+     # VALID_ARGUMENTS=$?
+     #if [ "$VALID_ARGUMENTS" != "0" ] ; then f_print_usage ; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
 
 # Note about next command: 
 # By reading that set of standardised arguments into the shell's input arguments 
@@ -116,21 +139,36 @@ eval set -- "$PARSED_ARGUMENTS"
 
 while : ; do
     case "$1" in
-      -h | --help )  # Help, if you're so stupid that you don't get that :)
+#       -f | --file )
+#          MODE=file
+#          string=$(cat "$2")
+#          shift 2
+#           ;;   
+#       -s | --string )
+#          MODE=string
+#          string="$2"
+#          shift 2
+#           ;;   
+#       -i | --input ) # Doesn't do anything here because it's dealt with in default above.
+#          shift 1
+#           ;;   
+       -h | --help )  # Help, if you're so stupid that you don't get that :)
            f_print_usage
            exit $EXIT_CODE_SUCCESS
            ;;   
       -v | --version)  # Version number
-           echo $PROGRAM_NAME: version $VERSION_NUMBER >&2
+           echo $(basename $0): version $VERSION_NUMBER >&2
            exit $EXIT_CODE_SUCCESS
            ;;
 #      -q | --quiet)  # Quiet mode
+#          ##### DROP THIS OPTION?
 #           QUIET_MODE=true
 #           REDIRECT="/dev/null"
 #           ARGS+=" --quiet"
 #           shift # Only one (default) shift for a switch, i.e., no argument
 #           ;;
 #      -V | --verbose)  # Verbose mode
+#          ##### DROP THIS OPTION?
 #           VERBOSE_MODE=true
 #           shift # Only one (default) shift for a switch, i.e., no argument
 #           ;;
@@ -155,33 +193,32 @@ done
 #   We haven't yet tested for the existence of required options and/or remaining arguments (now $1, $2, etc.)
 #   We also haven't yet tested for the valid options arguments and/or remaining arguments (now $1, $2, etc.)
 
-string="$1"
-num_chars="$2"
-
 # Review this.
 # CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
-if [ $# -ne 2 ]; then
-	f_print_usage "Invalid number of arguments."
+if [ $# -ne 2 ] ; then
+	f_print_usage "Must have exactly two arguments."
 	exit $EXIT_CODE_INVALID_ARGUMENTS
      fi
 
-if [[ -z "$string" || -z "$num_chars" ]] || [ $# -ne 2 ] ; then
-	f_print_usage "Takes exactly two parameters."
-     exit $EXIT_CODE_EPERM
+search_string="$1"
+filename="$2"
+
+if ! test -f "$filename" ; then
+	f_print_usage "File not found."
+	exit $EXIT_CODE_FILE_NOT_FOUND
      fi
 
-if ! [[ "$num_chars" =~ ^[0-9]+$ ]] ; then
-	f_print_usage "Number of characters must be a non-negative integer."
-     exit $EXIT_CODE_EPERM
-     fi
-
-if (( num_chars > ${#string} )) ; then
-     num_chars=${#string}
-     fi
-  
-printf "%s" "${string:0:$num_chars}"
-if [ $(cursor --column) -ne 0 ] ; then
-     echo "" >&2 # This allows piping the result above to another program, and only issue a newline to the console.
+haystack=$(cat "$filename")
+rest=${haystack#*$search_string}
+start_byte=$(( ${#haystack} + 1 - ${#rest} - ${#search_string} ))
+if [ $start_byte -gt 0 ] ; then
+     printf "%d" $start_byte;
+     if [ $(cursor --column) -ne 0 ] ; then
+          echo "" >&2 # This allows piping the result above to another program, and only issue a newline to the console.
+          exit $EXIT_CODE_SUCCESS
+          fi
+     else
+          exit -1
      fi
 
 
diff --git a/sbin/mid b/sbin/mid
--- a/sbin/mid
+++ b/sbin/mid
@@ -29,8 +29,8 @@
 # Basic Setup
 
 ### FILL IN THESE VARIABLES!!! ###
-     PURPOSE="Displays the first <number-of-characters> characters of a string." # Don't include $0, e.g., "Saves the world" 
-     USAGE="[-hv --help --version] <source-string> <number-of-characters>" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
+     PURPOSE="Displays a substring of a source string" # Don't include $0, e.g., "Saves the world" 
+     USAGE="[-hv --help --version] <source-string> <start-position> <length>" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
      VERSION_NUMBER="0.1"
      COLOPHON="$(printf "\u00A9") $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
      ROOT_REQUIRED=false
@@ -70,19 +70,21 @@
 ###################################################
 # Functions
 
-# EDIT THIS!
 function f_print_usage {
   printf "%s" "$PROGRAM_NAME $VERSION_NUMBER" >&2
-  if [ $# -gt 0 ] ; then echo ": Error: $1" >&2 ; else echo "" >&2 ; fi
+  if [ $# -gt 0 ] ; then echo ": Error: $1" ; else echo "" ; fi
   echo $COLOPHON >&2
   echo Usage: $PROGRAM_NAME $USAGE >&2
+  ##### Not standard! DROP?
+  echo "   NOTE: The first character in the source string is at start position 1, not 0." >&2
+
   echo Purpose: $PURPOSE >&2
   if $ROOT_REQUIRED ; then echo Requires root or sudo. >&2 ; fi
   echo "Options:" >&2
-  echo "  -v --version  Display version number, then exit (no other options processed)" >&2
-  echo "  -h --help     Display usage and help information, then exit (no other options processed)" >&2
-  echo "Example usage: " $PROGRAM_NAME supercalifragilisticexpialidocious 5 >&2
-}
+    echo "  -v --version  Display version number, then exit (no other options processed)" >&2
+    echo "  -h --help     Display usage and help information, then exit (no other options processed)" >&2
+  echo "Example usage:  $PROGRAM_NAME \"This is the day\" 6 2">&2
+  }
 
 
 ###################################################
@@ -101,13 +103,13 @@ function f_print_usage {
 #   Colon after an option means an argument is required. 
 #       In this example, options A, B, and C are switches; a, b, and c expect arguments
 #       Similarly for long options, options optionA, optionB, and optionC are switches; optiona, optionb, and optionc expect arguments
-#   Double Colon after an option means an argument is optional.
+#   Double Colon after an option means an argument is optional. 
 #   The '-- "$@"' at the end means that all other command arguments are "remaining arguments".
 PARSED_ARGUMENTS=$(getopt --name $PROGRAM_NAME --options hv \
     --long help,version \
     -- "$@")
 VALID_ARGUMENTS=$?
-if [ "$VALID_ARGUMENTS" != "0" ] ; then f_print_usage "Invalid arguments" ; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
+if [ "$VALID_ARGUMENTS" != "0" ] ; then f_print_usage ; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
 
 # Note about next command: 
 # By reading that set of standardised arguments into the shell's input arguments 
@@ -121,19 +123,9 @@ while : ; do
            exit $EXIT_CODE_SUCCESS
            ;;   
       -v | --version)  # Version number
-           echo $PROGRAM_NAME: version $VERSION_NUMBER >&2
+           echo "$PROGRAM_NAME: version $VERSION_NUMBER" >&2
            exit $EXIT_CODE_SUCCESS
            ;;
-#      -q | --quiet)  # Quiet mode
-#           QUIET_MODE=true
-#           REDIRECT="/dev/null"
-#           ARGS+=" --quiet"
-#           shift # Only one (default) shift for a switch, i.e., no argument
-#           ;;
-#      -V | --verbose)  # Verbose mode
-#           VERBOSE_MODE=true
-#           shift # Only one (default) shift for a switch, i.e., no argument
-#           ;;
       --) # -- means the end of the arguments; drop this, and break out of the while loop
            shift
            break 
@@ -155,31 +147,20 @@ done
 #   We haven't yet tested for the existence of required options and/or remaining arguments (now $1, $2, etc.)
 #   We also haven't yet tested for the valid options arguments and/or remaining arguments (now $1, $2, etc.)
 
-string="$1"
-num_chars="$2"
-
-# Review this.
 # CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
-if [ $# -ne 2 ]; then
-	f_print_usage "Invalid number of arguments."
+if [ $# -ne 3 ] ; then
+	f_print_usage "Wrong number of arguments"
 	exit $EXIT_CODE_INVALID_ARGUMENTS
      fi
 
-if [[ -z "$string" || -z "$num_chars" ]] || [ $# -ne 2 ] ; then
-	f_print_usage "Takes exactly two parameters."
-     exit $EXIT_CODE_EPERM
-     fi
+string="$1"
+offset="$(($2-1))"
+length="$3"
 
-if ! [[ "$num_chars" =~ ^[0-9]+$ ]] ; then
-	f_print_usage "Number of characters must be a non-negative integer."
-     exit $EXIT_CODE_EPERM
-     fi
-
-if (( num_chars > ${#string} )) ; then
-     num_chars=${#string}
-     fi
-  
-printf "%s" "${string:0:$num_chars}"
+source_string="$string"
+start_position="$offset"
+substring="${source_string:start_position:length}"
+printf "%s" "$substring"
 if [ $(cursor --column) -ne 0 ] ; then
      echo "" >&2 # This allows piping the result above to another program, and only issue a newline to the console.
      fi
diff --git a/sbin/right b/sbin/right
--- a/sbin/right
+++ b/sbin/right
@@ -32,7 +32,9 @@
      PURPOSE="Displays the last <number-of-characters> characters of a string." # Don't include $0, e.g., "Saves the world" 
      USAGE="[-hv --help --version] <source-string> <number-of-characters>" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
      VERSION_NUMBER="0.1"
-     COLOPHON="(c) $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
+     COLOPHON="$(printf "\u00A9") $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
+     ROOT_REQUIRED=false
+     VERBOSE_MODE=false
 
 # Stable variables; OK to leave this in without edits.
      ARGS="" # Adapted when flags are parsed.
@@ -63,7 +65,6 @@
      PROGRAM_NAME="$(basename $0)"
      QUIET_MODE=false
      REDIRECT="/dev/stdout" # Switch to "/dev/null" for quiet mode. This is where text that could be suppressed by quiet mode is directed. 
-     VERBOSE_MODE=false
 
 
 ###################################################
@@ -71,42 +72,17 @@
 
 # EDIT THIS!
 function f_print_usage {
-  echo "$PROGRAM_NAME version $VERSION_NUMBER" >&2
+  printf "%s" "$PROGRAM_NAME $VERSION_NUMBER" >&2
+  if [ $# -gt 0 ] ; then echo ": Error: $1" >&2 ; else echo "" >&2 ; fi
+  echo $COLOPHON >&2
   echo Usage: $PROGRAM_NAME $USAGE >&2
   echo Purpose: $PURPOSE >&2
-#  echo Requires root or sudo. >&2 #OPTIONAL!
-  echo >&2
+  if $ROOT_REQUIRED ; then echo Requires root or sudo. >&2 ; fi
   echo "Options:" >&2
-#  echo "  -q --quiet                        Mimimal output" >&2
-#  echo "  -V --verbose                      Verbose output" >&2
   echo "  -v --version  Display version number, then exit (no other options processed)" >&2
   echo "  -h --help     Display usage and help information, then exit (no other options processed)" >&2
-  echo >&2
   echo "Example usage: " $PROGRAM_NAME snapshot 4 >&2
-  echo >&2 ; echo $COLOPHON >&2
 }
-
-# OK as is; no need to update
-function f_alert () {
-	# Information for user.
-     # Variable 1: Error or other message (e.g., "File not found")
-     echo "$PROGRAM_NAME version $VERSION_NUMBER: $1" >&2
-	echo "Usage: $PROGRAM_NAME $USAGE" >&2
-     echo "Purpose: $PURPOSE" >&2
-     echo "$COLOPHON" >&2
-	}
-
-
-###################################################
-# General error testing
-
-# # Review this.
-# # CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
-# if [ $# -ne 0 ]; 
-#      then echo "Invalid number of arguments." >&2
-# 	f_print_usage
-# 	exit $EXIT_CODE_INVALID_ARGUMENTS
-# fi
 
 
 ###################################################
@@ -131,7 +107,7 @@ PARSED_ARGUMENTS=$(getopt --name $PROGRAM_NAME --options hv \
     --long help,version \
     -- "$@")
 VALID_ARGUMENTS=$?
-if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
+if [ "$VALID_ARGUMENTS" != "0" ] ; then f_print_usage "Invalid arguments" ; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
 
 # Note about next command: 
 # By reading that set of standardised arguments into the shell's input arguments 
@@ -163,7 +139,7 @@ while : ; do
            break 
            ;;
       *) # Invalid option.
-          f_alert "Invalid option."
+          f_print_usage "Invalid option."
           exit EXIT_CODE_INVALID_OPTIONS
            ;;
   esac
@@ -184,26 +160,19 @@ num_chars="$2"
 
 # Review this.
 # CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
-if [ $# -ne 2 ]; 
-     then echo "Invalid number of arguments." >&2
-	f_print_usage
+if [ $# -ne 2 ] ; then 
+	f_print_usage "Invalid number of arguments."
 	exit $EXIT_CODE_INVALID_ARGUMENTS
      fi
 
 if [[ -z "$string" || -z "$num_chars" ]] || [ $# -ne 2 ]; then
-     echo "$PROGRAM_NAME: Takes exactly two parameters" >&2
-     echo "by Lane Hensley, lane@lanehensley.org, https://lanehensley.org" >&2
-     echo "Usage: $PROGRAM_NAME <string> <number_of_characters>" >&2
-     echo "Purpose: Displays the first <number_of_characters> characters of a string." >&2
-     exit 1
+	f_print_usage "Takes exactly two parameters"
+     exit $EXIT_CODE_EPERM
 fi
 
 if ! [[ "$num_chars" =~ ^[0-9]+$ ]]; then
-     echo "$PROGRAM_NAME: Number of characters must be a non-negative integer." >&2
-     echo "by Lane Hensley, lane@lanehensley.org, https://lanehensley.org" >&2
-	echo "Usage: $PROGRAM_NAME <string> <number_of_characters>" >&2
-     echo "Purpose: Displays the first <number_of_characters> characters of a string." >&2
-     exit 1
+	f_print_usage "Number of characters must be a non-negative integer."
+     exit $EXIT_CODE_EPERM
 fi
 
 if (( num_chars > ${#string} )); then
@@ -211,7 +180,10 @@ if (( num_chars > ${#string} )); then
 fi
   
 backward=$(echo $string | rev)
-echo "${backward:0:$num_chars}" | rev
+printf "%s" $("${backward:0:$num_chars}" | rev)
+if [ $(cursor --column) -ne 0 ] ; then
+     echo "" >&2 # This allows piping the result above to another program, and only issue a newline to the console.
+     fi
 
 
 ###################################################
diff --git a/sbin/string-escape b/sbin/string-escape
--- a/sbin/string-escape
+++ b/sbin/string-escape
@@ -29,12 +29,13 @@
 # Basic Setup
 
 ### FILL IN THESE VARIABLES!!! ###
-     COLOPHON="(c) $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
-     PURPOSE="Adds escape codes to a string" # Don't include $0, e.g., "Prints the first 5 characters of a string" 
+     COLOPHON="$(printf "\u00A9") $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
+     PURPOSE="Renders an escaped-characters version of a string" # Don't include $0, e.g., "Prints the first 5 characters of a string" 
      USAGE="[-ifshv --input --file= --string= --help --version]" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
      VERSION_NUMBER="0.1"
      QUIET_MODE=false
      VERBOSE_MODE=false
+     ROOT_REQUIRED=false
 
 # Stable variables; OK to leave this in without edits.
      ARGS="" # Adapted when flags are parsed.
@@ -62,65 +63,40 @@
      EXIT_CODE_FILE_IN_USE=171
      EXIT_CODE_WRONG_HOST=172
      EXIT_CODE_INVALID_ARGUMENTS=173
-     PROGRAM_NAME=$(basename "$0")
+     PROGRAM_NAME="$(basename $0)"
+     QUIET_MODE=false
      REDIRECT="/dev/stdout" # Switch to "/dev/null" for quiet mode. This is where text that could be suppressed by quiet mode is directed. 
+
 
 ###################################################
 # Functions
 # EDIT THIS!
 
 function f_print_usage {
-  echo "$PROGRAM_NAME version $VERSION_NUMBER" >&2
+  printf "%s" "$PROGRAM_NAME $VERSION_NUMBER" >&2
+  if [ $# -gt 0 ] ; then echo ": Error: $1" >&2 ; else echo "" >&2 ; fi
+  echo $COLOPHON >&2
   echo Usage: $PROGRAM_NAME $USAGE >&2
   echo Purpose: $PURPOSE >&2
-#  echo Requires root or sudo. >&2
-  echo >&2
+  if $ROOT_REQUIRED ; then echo Requires root or sudo. >&2 ; fi
   echo "Options:" >&2
   echo "  -i --input                                      Use standard input for input (default)" >&2
   echo "  -f<source-file-name> --file=<source-file-name>  Use specified file contents for input" >&2
   echo "  -s<source-string> --string=<source-string>      Use specified string for input" >&2
-  echo "    IMPORTANT: The three lines above are mutually exclusive. Detault is -i or --input" >&2
-#  echo "  -q --quiet                                        Mimimal output" >&2
+  echo "     IMPORTANT: The three lines above are mutually exclusive. Default is -i or --input." >&2
+#  echo "  -q --quiet                                        Minimal output" >&2
 #  echo "  -V --verbose                                      Verbose output" >&2
-  echo "  -v --version                                      Display version number, then exit" >&2
+  echo "  -v --version                                    Display version number, then exit" >&2
 #  echo "                                                    (no other options processed)" >&2
   echo "  -h --help                                       Display usage and help information," >&2
   echo "                                                  then exit (no other options processed)" >&2
-  echo >&2
-  echo "Example usages: echo \$string |" $(basename "$0") -i >&2
-  echo "                echo \$string |" $(basename "$0") --input >&2
-  echo "                cat <filename> |" $(basename "$0") -i >&2
-  echo "                cat <filename> |" $(basename "$0") --input >&2
-  echo "                "$(basename "$0") -f\<source-file-name\> >&2
-  echo "                "$(basename "$0") -file=\<source-file-name\> >&2
-  echo "                "$(basename "$0") -s\<\$source-string\> >&2
-  echo "                "$(basename "$0") -string=\<\$source-string\> >&2
-     #  # Describe any exit codes returned. For examples below, comment out any unused values. EXAMPLE:
-     #  echo Return values: >&2
-     #  echo "  " $EXIT_CODE_SUCCESS on success, >&2
-     #  echo "  " $EXIT_CODE_INTERNAL_ERROR on internal error, >&2
-     #  echo "  " $EXIT_CODE_INVALID_OPTIONS if invalid options specified, >&2
-     #  echo "  " $EXIT_CODE_ROOT_REQUIRED if root required, >&2
-     #  # echo "  " $EXIT_CODE_UBUNTU_REQUIRED if Ubuntu required, >&2
-     #  # echo "  " $EXIT_CODE_MINIMUM_OS_VERSION_REQUIRED if minimum OS version required, >&2
-     #  # echo "  " $EXIT_CODE_MAXIMUM_OS_VERSION_REQUIRED if maximum OS version required, >&2
-     #  # echo "  " $EXIT_CODE_SPECIFIC_SERVER_REQUIRED if specific server required, >&2
-     #  # echo "  " $EXIT_CODE_FILE_NOT_FOUND if file not found, >&2
-     #  # echo "  " $EXIT_CODE_DIRECTORY_NOT_FOUND if directory not found, >&2
-     #  # echo "  " $EXIT_CODE_FILE_IN_USE if file in use, >&2
-     #  echo "  " $EXIT_CODE_USER_ABORT on user abort >&2
-     #  echo >&2
-   echo  >&2 ; echo $COLOPHON >&2
+  echo "Example usages: echo \$string |" $PROGRAM_NAME >&2
+  echo "                cat <filename> |" $PROGRAM_NAME >&2
+  echo "                "$PROGRAM_NAME -f\<source-file-name\> >&2
+  echo "                "$PROGRAM_NAME -file=\<source-file-name\> >&2
+  echo "                "$PROGRAM_NAME -s\<\$source-string\> >&2
+  echo "                "$PROGRAM_NAME -string=\<\$source-string\> >&2
  }
-
-function f_alert () {
-	# Information for user.
-     # Variable 1: Error or other message (e.g., "File not found")
-     echo "$(basename $0) version $VERSION_NUMBER: $1" >&2
-	echo "Usage: $(basename $0) $USAGE" >&2
-     echo "Purpose: $PURPOSE" >&2
-     echo "$COLOPHON" >&2
-	}
 
 
 ###################################################
@@ -145,7 +121,7 @@ PARSED_ARGUMENTS=$(getopt --name $(basename "$0") --options f:his:v \
     --long file:,help,input,string:,version \
     -- "$@")
 VALID_ARGUMENTS=$?
-if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
+if [ "$VALID_ARGUMENTS" != "0" ] ; then f_print_usage "Invalid arguments" ; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
 
 # Note about next command: 
 # By reading that set of standardised arguments into the shell's input arguments 
@@ -201,7 +177,7 @@ while : ; do
            break 
            ;;
       *) # Invalid option.
-          f_alert "Invalid option."
+          f_print_usage "Invalid option."
           exit EXIT_CODE_INVALID_OPTIONS
            ;;
   esac
