upd

diff --git a/sbin/^template_with_getopt_no_head_foot b/sbin/^template_with_getopt_no_head_foot
--- a/sbin/^template_with_getopt_no_head_foot
+++ b/sbin/^template_with_getopt_no_head_foot
@@ -3,6 +3,7 @@
 ###################################################
 # Notes
 #
+# USE "getopt", NOT "getopts" !
 # "getopts" is built into shell, which makes it run faster then "getopt", which is an external command
 # But "getopts" does not support long command line arguments (e.g., shellscriptname --argument=value)
 # STRONG RECOMMENDATION: Use getopt and not getopts
@@ -29,13 +30,13 @@
 
 ### FILL IN THESE VARIABLES!!! ###
      COLOPHON="(c) $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
-     PURPOSE="Sample purpose" # Don't include $0, e.g., "Prints the first 5 characters of a string" 
-     USAGE="Sample usage" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>"
+     PURPOSE="SAMPLE PURPOSE" # Don't include $0, e.g., "Prints the first 5 characters of a string" 
+     USAGE="SAMPLE USAGE" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
      VERSION_NUMBER="0.1"
      QUIET_MODE=false
      VERBOSE_MODE=false
 
-# Global variables
+# Stable variables; OK to leave this in without edits.
      ARGS="" # Adapted when flags are parsed.
      EXIT_CODE_SUCCESS=0
      EXIT_CODE_EPERM=1 # Operation not permitted
@@ -60,63 +61,73 @@
      EXIT_CODE_DIRECTORY_NOT_FOUND=170
      EXIT_CODE_FILE_IN_USE=171
      EXIT_CODE_WRONG_HOST=172
+     EXIT_CODE_INVALID_ARGUMENTS=173
      REDIRECT="/dev/stdout" # Switch to "/dev/null" for quiet mode. This is where text that could be suppressed by quiet mode is directed. 
 
-############## IMPORTANT: See "FILL THIS IN!!!!!" below. ##############
-function f_alert () {
-	# Information for user.
-     # Variable 1: Error or other message (e.g., "File not found")
-     echo "$(basename $0) version $VERSION_NUMBER: $1" >&2
-     echo "$COLOPHON" >&2
-	echo "Usage: $(basename $0) $USAGE" >&2
-     echo "Purpose: $PURPOSE" >&2
-	}
-
-# CHECK FOR ENOUGH ARGUMENTS (change 0 to minimum arguments and flesh out Usage)
-if [ $# -lt 0 ]; 
-     then echo "$EXIT_CODE_DESC_DIRECTORY_NOT_FOUND"
-	echo "Usage: $(basename $0)"
-	exit $EXIT_CODE_DIRECTORY_NOT_FOUND
-fi
 
 ###################################################
 # Functions
 
+# EDIT THIS!
 function f_print_usage {
-  echo
-  echo Usage: $(basename "$0") [-hqVv --help --quiet --verbose --version]
-  echo "Version $VERSION_NUMBER"
-  echo Apply configureations and selected permissions on local system.
-  echo Requires root or sudo.
-  echo
-  echo "Options:"
-  echo "  -q --quiet                        Mimimal output"
-  echo "  -V --verbose                      Verbose output"
-  echo "  -v --version                      Display version number, then exit (no other options processed)"
-  echo "  --help                            Display usage and help information, then exit (no other options processed)"
-  echo
-  echo "Example usage: " $(basename "$0")
-  echo
+  echo >&2
+  echo Usage: $USAGE >&2
+  echo "Version: $VERSION_NUMBER" >&2
+  echo Purpose: $PURPOSE >&2
+  echo Requires root or sudo. >&2 #OPTIONAL!
+  echo >&2
+  echo "Options:" >&2
+  echo "  -q --quiet                        Mimimal output" >&2
+  echo "  -V --verbose                      Verbose output" >&2
+  echo "  -v --version                      Display version number, then exit (no other options processed)" >&2
+  echo "  -h --help                         Display usage and help information, then exit (no other options processed)" >&2
+  echo >&2
+  echo "Example usage: " $(basename "$0") >&2
+  echo >&2
      #  # Describe any exit codes returned. For examples below, comment out any unused values. EXAMPLE:
-     #  echo Return values:
-     #  echo "  " $EXIT_CODE_SUCCESS on success,
-     #  echo "  " $EXIT_CODE_INTERNAL_ERROR on internal error,
-     #  echo "  " $EXIT_CODE_INVALID_OPTIONS if invalid options specified,
-     #  echo "  " $EXIT_CODE_ROOT_REQUIRED if root required,
-     #  # echo "  " $EXIT_CODE_UBUNTU_REQUIRED if Ubuntu required,
-     #  # echo "  " $EXIT_CODE_MINIMUM_OS_VERSION_REQUIRED if minimum OS version required,
-     #  # echo "  " $EXIT_CODE_MAXIMUM_OS_VERSION_REQUIRED if maximum OS version required,
-     #  # echo "  " $EXIT_CODE_SPECIFIC_SERVER_REQUIRED if specific server required,
-     #  # echo "  " $EXIT_CODE_FILE_NOT_FOUND if file not found,
-     #  # echo "  " $EXIT_CODE_DIRECTORY_NOT_FOUND if directory not found,
-     #  # echo "  " $EXIT_CODE_FILE_IN_USE if file in use,
-     #  echo "  " $EXIT_CODE_USER_ABORT on user abort
-     #  echo
-  }
+     #  echo Return values: >&2
+     #  echo "  " $EXIT_CODE_SUCCESS on success, >&2
+     #  echo "  " $EXIT_CODE_INTERNAL_ERROR on internal error, >&2
+     #  echo "  " $EXIT_CODE_INVALID_OPTIONS if invalid options specified, >&2
+     #  echo "  " $EXIT_CODE_ROOT_REQUIRED if root required, >&2
+     #  # echo "  " $EXIT_CODE_UBUNTU_REQUIRED if Ubuntu required, >&2
+     #  # echo "  " $EXIT_CODE_MINIMUM_OS_VERSION_REQUIRED if minimum OS version required, >&2
+     #  # echo "  " $EXIT_CODE_MAXIMUM_OS_VERSION_REQUIRED if maximum OS version required, >&2
+     #  # echo "  " $EXIT_CODE_SPECIFIC_SERVER_REQUIRED if specific server required, >&2
+     #  # echo "  " $EXIT_CODE_FILE_NOT_FOUND if file not found, >&2
+     #  # echo "  " $EXIT_CODE_DIRECTORY_NOT_FOUND if directory not found, >&2
+     #  # echo "  " $EXIT_CODE_FILE_IN_USE if file in use, >&2
+     #  echo "  " $EXIT_CODE_USER_ABORT on user abort >&2
+     #  echo >&2
+    echo >&2 ; echo $COLOPHON >&2
+}
+
+# OK as is; no need to update
+function f_alert () {
+	# Information for user.
+     # Variable 1: Error or other message (e.g., "File not found")
+     echo "$(basename $0) version $VERSION_NUMBER: $1" >&2
+	echo "Usage: $(basename $0) $USAGE" >&2
+     echo "Purpose: $PURPOSE" >&2
+     echo "$COLOPHON" >&2
+	}
+
+
+###################################################
+# General error testing
+
+# Review this.
+# CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
+if [ $# -ne 0 ]; 
+     then echo "Invalid number of arguments." >&2
+	f_print_usage
+	exit $EXIT_CODE_INVALID_ARGUMENTS
+fi
 
 
 ###################################################
 # Parse options and arguments with getopt
+# READ AND EDIT THIS!
 
 # Note about the following call to getopt
 #   Options used here with the getopt command itself
@@ -130,8 +141,9 @@ function f_print_usage {
 #   Colon after an option means an argument is required. 
 #       In this example, options A, B, and C are switches; a, b, and c expect arguments
 #       Similarly for long options, options optionA, optionB, and optionC are switches; optiona, optionb, and optionc expect arguments
+#   Double Colon after an option means an argument is optional. 
 #   The '-- "$@"' at the end means that all other command arguments are "remaining arguments".
-PARSED_ARGUMENTS=$(getopt --name $(basename "$0") --options Vvq \
+PARSED_ARGUMENTS=$(getopt --name $(basename "$0") --options hqVv \
     --long help,quiet,verbose,version \
     -- "$@")
 VALID_ARGUMENTS=$?
@@ -144,12 +156,12 @@ eval set -- "$PARSED_ARGUMENTS"
 
 while : ; do
     case "$1" in
-      -h | --help )
+      -h | --help )  # Help, if you're so stupid that you don't get that :)
            f_print_usage
            exit $EXIT_CODE_SUCCESS
            ;;   
       -v | --version)  # Version number
-           echo $VERSION_NUMBER
+           echo $(basename $0): version $VERSION_NUMBER >&2
            exit $EXIT_CODE_SUCCESS
            ;;
       -q | --quiet)  # Quiet mode
@@ -166,7 +178,9 @@ while : ; do
            shift
            break 
            ;;
-      *) f_die "Unexpected option: $1 - Script programming error. Valid option has no handler." false $EXIT_CODE_INTERNAL_ERROR
+      *) # Invalid option.
+          f_alert "Invalid option."
+          exit EXIT_CODE_INVALID_OPTIONS
            ;;
   esac
 done
@@ -181,17 +195,9 @@ done
 #   We haven't yet tested for the existence of required options and/or remaining arguments (now $1, $2, etc.)
 #   We also haven't yet tested for the valid options arguments and/or remaining arguments (now $1, $2, etc.)
 
-echo "I don't do anything yet."
-
-printf "%q" "$string"
-
-# i = stdio, s = string, f = file (can't be combined; default = s)
-# h = help, v = version
+echo "I don't do anything yet." >&2
 
 ###################################################
 # Wrap up.
-
-# Option to text the administrator when the script ends
-# echo "[$(hostname)] $(basename $0): completed" | mail "$ADMIN_CELL_EMAIL"
 
 exit 0
diff --git a/sbin/cursor b/sbin/cursor
--- a/sbin/cursor
+++ b/sbin/cursor
@@ -30,8 +30,8 @@
 
 ### FILL IN THESE VARIABLES!!! ###
      COLOPHON="(c) $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
-     PURPOSE="Adds escape codes to a string" # Don't include $0, e.g., "Prints the first 5 characters of a string" 
-     USAGE="[-ifshv --input --file= --string= --help --version]" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
+     PURPOSE="Displays the row or column cursor position, top left being 0 0" # Don't include $0, e.g., "Prints the first 5 characters of a string" 
+     USAGE="[-crhv --column --row --help --version]" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
      VERSION_NUMBER="0.1"
      QUIET_MODE=false
      VERBOSE_MODE=false
@@ -64,46 +64,32 @@
      EXIT_CODE_INVALID_ARGUMENTS=173
      REDIRECT="/dev/stdout" # Switch to "/dev/null" for quiet mode. This is where text that could be suppressed by quiet mode is directed. 
 
-function f_alert () {
-	# Information for user.
-     # Variable 1: Error or other message (e.g., "File not found")
-     echo "$(basename $0) version $VERSION_NUMBER: $1" >&2
-	echo "Usage: $(basename $0) $USAGE" >&2
-     echo "Purpose: $PURPOSE" >&2
-     echo "$COLOPHON" >&2
-	}
-
 ###################################################
 # Functions
-# EDIT THIS!
 
+# EDIT THIS!
 function f_print_usage {
   echo >&2
   echo Usage: $USAGE >&2
-  echo Version: $VERSION_NUMBER >&2
+  echo "Version: $VERSION_NUMBER" >&2
   echo Purpose: $PURPOSE >&2
-#  echo Requires root or sudo. >&2
+#  echo Requires root or sudo. >&2 #OPTIONAL!
   echo >&2
   echo "Options:" >&2
-  echo "  -i --input                                      Use standard input for input (default)" >&2
-  echo "  -f<source-file-name> --file=<source-file-name>  Use specified file contents for input" >&2
-  echo "  -s<source-string> --string=<source-string>      Use specified string for input" >&2
-  echo "    IMPORTANT: The three lines above are mutually exclusive. Detault is -i or --input" >&2
-#  echo "  -q --quiet                                        Mimimal output" >&2
-#  echo "  -V --verbose                                      Verbose output" >&2
-  echo "  -v --version                                      Display version number, then exit" >&2
-#  echo "                                                    (no other options processed)" >&2
-  echo "  -h --help                                       Display usage and help information," >&2
-  echo "                                                  then exit (no other options processed)" >&2
+#  echo "  -q --quiet                        Mimimal output" >&2
+#  echo "  -V --verbose                      Verbose output" >&2
+  echo "  -c --column   Display column (default, and overrides -r or --row if -c or --column selected)" >&2
+  echo "  -r --row      Display row (works only if neither -c nor --column selected)" >&2
+  echo "  -v --version  Display version number, then exit (no other options processed)" >&2
+  echo "  -h --help     Display usage and help information, then exit (no other options processed)" >&2
   echo >&2
-  echo "Example usages: echo \$string |" $(basename "$0") -i >&2
-  echo "                echo \$string |" $(basename "$0") --input >&2
-  echo "                cat <filename> |" $(basename "$0") -i >&2
-  echo "                cat <filename> |" $(basename "$0") --input >&2
-  echo "                "$(basename "$0") -f\<source-file-name\> >&2
-  echo "                "$(basename "$0") -file=\<source-file-name\> >&2
-  echo "                "$(basename "$0") -s\<\$source-string\> >&2
-  echo "                "$(basename "$0") -string=\<\$source-string\> >&2
+  echo "Example usage: " $(basename "$0") -c >&2
+  echo "               " $(basename "$0") --column >&2
+  echo "               " $(basename "$0") -r >&2
+  echo "               " $(basename "$0") --row >&2
+  echo "               " $(basename "$0") -c -r >&2
+  echo "               " $(basename "$0") --column --row >&2
+  echo >&2
      #  # Describe any exit codes returned. For examples below, comment out any unused values. EXAMPLE:
      #  echo Return values: >&2
      #  echo "  " $EXIT_CODE_SUCCESS on success, >&2
@@ -119,8 +105,22 @@ function f_print_usage {
      #  # echo "  " $EXIT_CODE_FILE_IN_USE if file in use, >&2
      #  echo "  " $EXIT_CODE_USER_ABORT on user abort >&2
      #  echo >&2
-   echo  >&2 ; echo $COLOPHON >&2
- }
+  echo >&2 ; echo $COLOPHON >&2
+  }
+
+# OK as is; no need to update
+function f_alert () {
+	# Information for user.
+     # Variable 1: Error or other message (e.g., "File not found")
+     echo "$(basename $0) version $VERSION_NUMBER: $1" >&2
+     echo "$COLOPHON" >&2
+	echo "Usage: $(basename $0) $USAGE" >&2
+     echo "Purpose: $PURPOSE" >&2
+	}
+
+
+###################################################
+# General error testing
 
 ###################################################
 # Parse options and arguments with getopt
@@ -140,8 +140,8 @@ function f_print_usage {
 #       Similarly for long options, options optionA, optionB, and optionC are switches; optiona, optionb, and optionc expect arguments
 #   Double Colon after an option means an argument is optional. 
 #   The '-- "$@"' at the end means that all other command arguments are "remaining arguments".
-PARSED_ARGUMENTS=$(getopt --name $(basename "$0") --options f:his:v \
-    --long file:,help,input,string:,version \
+PARSED_ARGUMENTS=$(getopt --name $(basename "$0") --options crhv \
+    --long column,row,help,version \
     -- "$@")
 VALID_ARGUMENTS=$?
 if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
@@ -151,33 +151,33 @@ if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage; exit $EXIT_CODE_INVALID_AR
 #   the shell script now thinks that it was called with these simpler, standardised set of arguments.
 eval set -- "$PARSED_ARGUMENTS"
 
-# Setting default
-unset string
-if [[ -p /dev/stdin ]] || ! test -t 0 ; then  # Testing for anything at standard input
-     while IFS= read -r line; do
-          if [[ -z "$content" ]]; then
-               string="$line"
-               else string="$string"$'\n'"$line"
-               fi
-          done
-     fi
+#!/bin/bash
+# based on a script from http://invisible-island.net/xterm/xterm.faq.html
+exec < /dev/tty
+oldstty=$(stty -g)
+stty raw -echo min 0
+# on my system, the following line can be replaced by the line below it
+echo -en "\033[6n" > /dev/tty
+# tput u7 > /dev/tty    # when TERM=xterm (and relatives)
+IFS=';' read -r -d R -a pos
+stty $oldstty
+# change from one-based to zero based so they work with: tput cup $row $col
+rowval=$((${pos[0]:2} - 1))    # strip off the esc-[
+colval=$((${pos[1]} - 1))
 
+column=false
+row=false
 while : ; do
     case "$1" in
-       -f | --file )
-          MODE=file
-          string=$(cat "$2")
-          shift 2
-           ;;   
-       -s | --string )
-          MODE=string
-          string="$2"
-          shift 2
-           ;;   
-       -i | --input ) # Doesn't do anything here because it's dealt with in default above.
+      -c | --column )
+          column=true
           shift 1
            ;;   
-       -h | --help )  # Help, if you're so stupid that you don't get that :)
+      -r | --row )
+          row=true
+          shift 1
+           ;;   
+      -h | --help )  # Help, if you're so stupid that you don't get that :)
            f_print_usage
            exit $EXIT_CODE_SUCCESS
            ;;   
@@ -206,6 +206,11 @@ while : ; do
   esac
 done
 
+
+###################################################
+# Test for correct number of arguments.
+# IMPORTANT: You have to test this AFTER all the shifting above.
+
 # Review this.
 # CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
 if [ $# -ne 0 ]; 
@@ -224,13 +229,9 @@ fi
 #   We haven't yet tested for the existence of required options and/or remaining arguments (now $1, $2, etc.)
 #   We also haven't yet tested for the valid options arguments and/or remaining arguments (now $1, $2, etc.)
 
-printf "%d" ${#string}
-if [ $(cursor --column) -ne 0 ] ; then
-     echo "" >&2 # This allows piping the result above to another program, and only issue a newline to the console.
-     fi
-
-exit 0
-
+if $row && ! $column ; then
+     printf "%d" "$rowval"; else
+     printf "%d" "$colval"; fi
 
 ###################################################
 # Wrap up.
diff --git a/sbin/string-escape b/sbin/string-escape
--- a/sbin/string-escape
+++ b/sbin/string-escape
@@ -1,24 +1,239 @@
 #!/bin/bash
 
-DEBUG_MODE=false; if $DEBUG_MODE ; then echo "DEBUG EXECUTING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
+###################################################
+# Notes
+#
+# USE "getopt", NOT "getopts" !
+# "getopts" is built into shell, which makes it run faster then "getopt", which is an external command
+# But "getopts" does not support long command line arguments (e.g., shellscriptname --argument=value)
+# STRONG RECOMMENDATION: Use getopt and not getopts
+#
+# DEPRECATED: Initially followed tutorial at https://www.shellscript.sh/tips/getopt/
+# New Tutorial: https://www.tutorialspoint.com/unix_commands/getopt.htm
+# man page for getopt is at https://man7.org/linux/man-pages/man1/getopt.1.html
+#
+# Defining terms
+#    argument: any text appended to a command (syn.: parameter)
+#    parameter: synonym for argument
+#    option: a command argument preceded by a single or double hyphen (e.g., -o, or --option)
+#       An option may have an argument of its own (an "option argument", e.g., -o value-o, or --option value-o, or --option=value-o)
+#       All options are arguments, but not all arguments are options.
+#    short option: an option consisting of single hyphen and letter, with or without an option argument specified (e.g., -a value-a -b)
+#    long option: an option consisting of a double hyphen and word, with or without an option argument specified (e.g., --arga value-a --argb=value-b --argc)
+#    switch: a short or long option, with no option argument specified (e.g., -a --argb)
+#       All switches are options, but not all options are switches.
+#    remaining arguments: command line arguments that are neither options nor option arguments
 
-# Do stuff here
-if $DEBUG_MODE ; then echo "DEBUG MARKER $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
 
-string="$1"
+###################################################
+# Basic Setup
 
-if [ $# -ne 1 ]; then
-    echo "$(basename $0): Takes exactly one parameter" >&2
-    echo "by Lane Hensley, lane@lanehensley.org, https://lanehensley.org" >&2
-	echo "Usage: $(basename $0) string" >&2
-    echo "Purpose: Adds escape codes to a string." >&2
-	exit 1
-    fi
+### FILL IN THESE VARIABLES!!! ###
+     COLOPHON="(c) $(date +%Y) by Lane Hensley, lane@lanehensley.org, https://lanehensley.org"
+     PURPOSE="Adds escape codes to a string" # Don't include $0, e.g., "Prints the first 5 characters of a string" 
+     USAGE="[-ifshv --input --file= --string= --help --version]" # Don't include $0, e.g., "[-hqVv --help --quiet --verbose --version] <arg1> <arg2> <arg3>" Can go to multiple lines with \n in the string.
+     VERSION_NUMBER="0.1"
+     QUIET_MODE=false
+     VERBOSE_MODE=false
+
+# Stable variables; OK to leave this in without edits.
+     ARGS="" # Adapted when flags are parsed.
+     EXIT_CODE_SUCCESS=0
+     EXIT_CODE_EPERM=1 # Operation not permitted
+     EXIT_CODE_ENOENT=2 # No such file or directory
+     EXIT_CODE_EIO=5 # Input/output error
+     EXIT_CODE_E2BIG=7 # Argument list too long
+     EXIT_CODE_EEXIST=17 # File exists
+     EXIT_CODE_ENOTDIR=20 # Not a directory
+     EXIT_CODE_EISDIR=21 # Is a directory
+     EXIT_CODE_EINVAL=22 # Invalid argument
+     EXIT_CODE_EFBIG=27 # File too large
+     EXIT_CODE_ERANGE=34 # Numerical result out of range
+     EXIT_CODE_INTERNAL_ERROR=161
+     EXIT_CODE_INVALID_OPTIONS=162
+     EXIT_CODE_ROOT_REQUIRED=163
+     EXIT_CODE_UBUNTU_REQUIRED=164
+     EXIT_CODE_MINIMUM_OS_VERSION_REQUIRED=165
+     EXIT_CODE_MAXIMUM_OS_VERSION_REQUIRED=166
+     EXIT_CODE_SPECIFIC_SERVER_REQUIRED=167
+     EXIT_CODE_USER_ABORT=168
+     EXIT_CODE_FILE_NOT_FOUND=169
+     EXIT_CODE_DIRECTORY_NOT_FOUND=170
+     EXIT_CODE_FILE_IN_USE=171
+     EXIT_CODE_WRONG_HOST=172
+     EXIT_CODE_INVALID_ARGUMENTS=173
+     REDIRECT="/dev/stdout" # Switch to "/dev/null" for quiet mode. This is where text that could be suppressed by quiet mode is directed. 
+
+###################################################
+# Functions
+# EDIT THIS!
+
+function f_print_usage {
+  echo >&2
+  echo Usage: $USAGE >&2
+  echo Version: $VERSION_NUMBER >&2
+  echo Purpose: $PURPOSE >&2
+#  echo Requires root or sudo. >&2
+  echo >&2
+  echo "Options:" >&2
+  echo "  -i --input                                      Use standard input for input (default)" >&2
+  echo "  -f<source-file-name> --file=<source-file-name>  Use specified file contents for input" >&2
+  echo "  -s<source-string> --string=<source-string>      Use specified string for input" >&2
+  echo "    IMPORTANT: The three lines above are mutually exclusive. Detault is -i or --input" >&2
+#  echo "  -q --quiet                                        Mimimal output" >&2
+#  echo "  -V --verbose                                      Verbose output" >&2
+  echo "  -v --version                                      Display version number, then exit" >&2
+#  echo "                                                    (no other options processed)" >&2
+  echo "  -h --help                                       Display usage and help information," >&2
+  echo "                                                  then exit (no other options processed)" >&2
+  echo >&2
+  echo "Example usages: echo \$string |" $(basename "$0") -i >&2
+  echo "                echo \$string |" $(basename "$0") --input >&2
+  echo "                cat <filename> |" $(basename "$0") -i >&2
+  echo "                cat <filename> |" $(basename "$0") --input >&2
+  echo "                "$(basename "$0") -f\<source-file-name\> >&2
+  echo "                "$(basename "$0") -file=\<source-file-name\> >&2
+  echo "                "$(basename "$0") -s\<\$source-string\> >&2
+  echo "                "$(basename "$0") -string=\<\$source-string\> >&2
+     #  # Describe any exit codes returned. For examples below, comment out any unused values. EXAMPLE:
+     #  echo Return values: >&2
+     #  echo "  " $EXIT_CODE_SUCCESS on success, >&2
+     #  echo "  " $EXIT_CODE_INTERNAL_ERROR on internal error, >&2
+     #  echo "  " $EXIT_CODE_INVALID_OPTIONS if invalid options specified, >&2
+     #  echo "  " $EXIT_CODE_ROOT_REQUIRED if root required, >&2
+     #  # echo "  " $EXIT_CODE_UBUNTU_REQUIRED if Ubuntu required, >&2
+     #  # echo "  " $EXIT_CODE_MINIMUM_OS_VERSION_REQUIRED if minimum OS version required, >&2
+     #  # echo "  " $EXIT_CODE_MAXIMUM_OS_VERSION_REQUIRED if maximum OS version required, >&2
+     #  # echo "  " $EXIT_CODE_SPECIFIC_SERVER_REQUIRED if specific server required, >&2
+     #  # echo "  " $EXIT_CODE_FILE_NOT_FOUND if file not found, >&2
+     #  # echo "  " $EXIT_CODE_DIRECTORY_NOT_FOUND if directory not found, >&2
+     #  # echo "  " $EXIT_CODE_FILE_IN_USE if file in use, >&2
+     #  echo "  " $EXIT_CODE_USER_ABORT on user abort >&2
+     #  echo >&2
+   echo  >&2 ; echo $COLOPHON >&2
+ }
+
+function f_alert () {
+	# Information for user.
+     # Variable 1: Error or other message (e.g., "File not found")
+     echo "$(basename $0) version $VERSION_NUMBER: $1" >&2
+	echo "Usage: $(basename $0) $USAGE" >&2
+     echo "Purpose: $PURPOSE" >&2
+     echo "$COLOPHON" >&2
+	}
+
+
+###################################################
+# Parse options and arguments with getopt
+# READ AND EDIT THIS!
+
+# Note about the following call to getopt
+#   Options used here with the getopt command itself
+#       --name : Script name, used for reporting errors
+#       --options : Definition of short options
+#       --longoptions (--long) : Definition of long options
+#   Options used used with the getopt command itself
+#       --alternative : Allow long options to start with a single '-'.
+#       --help : Display help text and exit.  No other output is generated.
+#       --quiet, --test, --unquoted, --version
+#   Colon after an option means an argument is required. 
+#       In this example, options A, B, and C are switches; a, b, and c expect arguments
+#       Similarly for long options, options optionA, optionB, and optionC are switches; optiona, optionb, and optionc expect arguments
+#   Double Colon after an option means an argument is optional. 
+#   The '-- "$@"' at the end means that all other command arguments are "remaining arguments".
+PARSED_ARGUMENTS=$(getopt --name $(basename "$0") --options f:his:v \
+    --long file:,help,input,string:,version \
+    -- "$@")
+VALID_ARGUMENTS=$?
+if [ "$VALID_ARGUMENTS" != "0" ]; then f_print_usage; exit $EXIT_CODE_INVALID_ARGUMENTS; fi
+
+# Note about next command: 
+# By reading that set of standardised arguments into the shell's input arguments 
+#   the shell script now thinks that it was called with these simpler, standardised set of arguments.
+eval set -- "$PARSED_ARGUMENTS"
+
+# Setting default
+unset string
+if [[ -p /dev/stdin ]] || ! test -t 0 ; then  # Testing for anything at standard input
+     while IFS= read -r line; do
+          if [[ -z "$content" ]]; then
+               string="$line"
+               else string="$string"$'\n'"$line"
+               fi
+          done
+     fi
+
+while : ; do
+    case "$1" in
+       -f | --file )
+          MODE=file
+          string=$(cat "$2")
+          shift 2
+           ;;   
+       -s | --string )
+          MODE=string
+          string="$2"
+          shift 2
+           ;;   
+       -i | --input ) # Doesn't do anything here because it's dealt with in default above.
+          shift 1
+           ;;   
+       -h | --help )  # Help, if you're so stupid that you don't get that :)
+           f_print_usage
+           exit $EXIT_CODE_SUCCESS
+           ;;   
+      -v | --version)  # Version number
+           echo $(basename $0): version $VERSION_NUMBER >&2
+           exit $EXIT_CODE_SUCCESS
+           ;;
+#      -q | --quiet)  # Quiet mode
+#           QUIET_MODE=true
+#           REDIRECT="/dev/null"
+#           ARGS+=" --quiet"
+#           shift # Only one (default) shift for a switch, i.e., no argument
+#           ;;
+#      -V | --verbose)  # Verbose mode
+#           VERBOSE_MODE=true
+#           shift # Only one (default) shift for a switch, i.e., no argument
+#           ;;
+      --) # -- means the end of the arguments; drop this, and break out of the while loop
+           shift
+           break 
+           ;;
+      *) # Invalid option.
+          f_alert "Invalid option."
+          exit EXIT_CODE_INVALID_OPTIONS
+           ;;
+  esac
+done
+
+# Review this.
+# CHECK FOR CORRECT NUMBER/RANGE OF ARGUMENTS
+if [ $# -ne 0 ]; 
+     then echo "Invalid number of arguments." >&2
+	f_print_usage
+	exit $EXIT_CODE_INVALID_ARGUMENTS
+fi
+
+
+###################################################
+# Do the work.
+# IMPORTANT NOTES: 
+#   Don't forget that you still can read and use environment variables!
+#       Best practice: Required values should be required on and read from the command line, not environment variables.
+#           Environment variables are fine for optional values.
+#   We haven't yet tested for the existence of required options and/or remaining arguments (now $1, $2, etc.)
+#   We also haven't yet tested for the valid options arguments and/or remaining arguments (now $1, $2, etc.)
 
 printf "%q" "$string"
-
-# i = stdio, s = string, f = file (can't be combined; default = s)
-# h = help, v = version
+if [ $(cursor --column) -ne 0 ] ; then
+     echo "" >&2 # This allows piping the result above to another program, and only issue a newline to the console.
+     fi
 
 exit 0
 
+
+###################################################
+# Wrap up.
+
+exit 0
