function f_move_one_file

diff --git a/sbin/_functions b/sbin/_functions
--- a/sbin/_functions
+++ b/sbin/_functions
@@ -174,48 +174,41 @@ function f_move_one_file () {
 	OUT_FILE="$ROOT_OUT_PATH/$RELATIVE_FILE"
 	NEW_DIRECTORY="$(dirname "$OUT_FILE")"
 
-	# So here are useful variables defined ...
-	# $IN_FILE
-	# $OUT_FILE
-	# $ROOT_IN_PATH
-	# $ROOT_OUT_PATH
-	# $RELATIVE_FILE
-
 	f_file_not_in_use "$IN_FILE"
+	f_require_file "$IN_FILE"
+	f_require_directory "$ROOT_IN_PATH"
 
 	# Only if the STORE file system is read-only
 	# f_mount_ro_fs_as_rw "$COLD_BACKUP_FILE_SYSTEM"
 
 	# Make the directory for out file
-	if [ ! -d "$NEW_DIRECTORY" ]; then
-	  mkdir -p "$NEW_DIRECTORY" # Create the directory for the out file
-	  exit_status=$?
-	  chown plex:plex "$NEW_DIRECTORY"
-	  chmod 664 "$NEW_DIRECTORY"
-	  if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
-		  logger "$0: FAILED to make $NEW_DIRECTORY"
-		  echo "$(date) $0: FAILED to make $NEW_DIRECTORY" | mail -r move-one-file text_alerts
-		  sleep 1
-		  echo "$NEW_DIRECTORY" | mail -r move-one-file text_alerts
-		  exit $exit_status
-		fi
+	mkdir -p "$NEW_DIRECTORY"
+	if [ $? -ne 0 ]; then # If mkdir failed failed ...
+	  logger "$0: FAILED making $NEW_DIRECTORY"
+	  >&2 echo "$0: FAILED making $NEW_DIRECTORY"
+	  # echo "$0: FAILED making $NEW_DIRECTORY" | mail -r move-one-file text_alerts
+	  sleep 10 # Add some time here in case we're racing through a failure loop.
+	  # echo "$NEW_DIRECTORY" | mail -r move-one-file text_alerts
+	  return
 	fi
+	chown plex:plex "$NEW_DIRECTORY"
+	chmod 664 "$NEW_DIRECTORY"
 
 	# Move $IN_FILE to $OUT_FILE
+	logger $0: Moving $(basename "$IN_FILE")
+	echo $0: Moving $(basename "$IN_FILE")
 	mv "$IN_FILE" "$OUT_FILE"
-	exit_status=$?
-	if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
+	if [ $? -ne 0 ]; then # If the move failed ...
 		logger "$0: FAILED to move $IN_FILE to $NEW_DIRECTORY"
-		echo "$(date) $0: Failed to move file" | mail -r move-one-file text_alerts
-		sleep 1
+		>&2 echo "$0: FAILED to move $IN_FILE to $NEW_DIRECTORY"
+		echo "$0: Failed to move file" | mail -r move-one-file text_alerts
 		echo "Infile $IN_FILE" | mail -r move-one-file text_alerts
 		echo "Outfile $OUT_FILE" | mail -r move-one-file text_alerts
-		exit $exit_status
-	  else
-		chown plex:plex "$OUT_FILE"
-		chmod 664 "$OUT_FILE"
-		logger $0: moved $(basename "$IN_FILE")
+	    sleep 10 # Add some time here in case we're racing through a failure loop.
+		return
 	  fi
+  	  chown plex:plex "$OUT_FILE"
+	  chmod 664 "$OUT_FILE"
 
 	# Only if the STORE file system is read-only
 	# f_mount_ro_fs_as_ro "$COLD_BACKUP_FILE_SYSTEM" $COLD_BACKUP_FS_READ_ONLY
