dbug

diff --git a/sbin/_functions b/sbin/_functions
--- a/sbin/_functions
+++ b/sbin/_functions
@@ -3,16 +3,17 @@
 # Bash functions for Lane applications
 
 # Check to ensure that variables are defined
-	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $($basename $0): Variables not defined. Aborting; logger -t "$($basename $0)": Variables not defined. Aborting; exit 1; fi
+	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $(basename $0): Variables not defined. Aborting; logger -t "$(basename $0)": Variables not defined. Aborting; exit 1; fi
 
 # Set a flag to confirm that the functions are not yet defined
 FUNCTIONS_ARE_DEFINED=false
 
 function f_log_and_echo () {
 # Usage f_log_and_echo "$MESSAGE_TO_STDERR_AND_LOG" "SEND_TEXT_ALERT_TRUE_OR_FALSE"
-	if $2; then echo $($basename $0): $1 | mail $TEXT_ALERTS; fi
-	logger -t "$($basename $0)" $1
-	>&2 echo $($basename $0): $1
+	if $2; then echo $(basename $0): $1 | mail $TEXT_ALERTS; fi
+	logger -t "$(basename $0)" $1
+	# >&2 echo $(basename $0): $1
+	echo $(basename $0): $1
 	}
 
 function f_beep () {
@@ -36,7 +37,7 @@ function f_die () {
 function f_debug () {
     # $1: message to log, only used when $DEBUG_MODE == true
     if [ ! $DEBUG_MODE ]; then
-        logger -t "$($basename $0)" DEBUG: $1
+        logger -t "$(basename $0)" DEBUG: $1
         fi
     }
 
@@ -45,7 +46,7 @@ function f_debug_variable () {
     # $2: variable_value ("$variable_name")
     # Example: f_debug_variable "var" "$var"
     if [ ! $DEBUG_MODE ]; then
-        logger -t "$($basename $0)" DEBUG: $1 = $2
+        logger -t "$(basename $0)" DEBUG: $1 = $2
         fi
     }
 
@@ -139,9 +140,9 @@ function f_local_copy() {
 
 function f_install() {
 	if ! [ -x "$(command -v $1)" ]; then   
-		logger -t "$($basename $0)" Installing $1
+		logger -t "$(basename $0)" Installing $1
 		DEBIAN_FRONTEND=noninteractive apt-get install -yq $1
-		logger -t "$($basename $0)" Installation of $1 done exit code $?
+		logger -t "$(basename $0)" Installation of $1 done exit code $?
 	fi
 	}
 
@@ -164,8 +165,8 @@ function f_mount_ro_fs_as_rw () {
 		fi
 	# If file system is not mounted read-write, fail
 		if [ ! $(findmnt "$FILE_SYSTEM" -n -o options | grep "rw,") ]; then
-			logger -t "$($basename $0)" FATAL: $FILE_SYSTEM is not mounted with rw option
-			echo $($basename $0): FATAL: $FILE_SYSTEM is not mounted with rw option
+			logger -t "$(basename $0)" FATAL: $FILE_SYSTEM is not mounted with rw option
+			echo $(basename $0): FATAL: $FILE_SYSTEM is not mounted with rw option
 			exit 1
 		fi
 	}
@@ -183,8 +184,8 @@ function f_mount_ro_fs_as_ro () {
 		fi
 	# If file system is not mounted read-only, fail
 		if [ ! $(findmnt "$FILE_SYSTEM" -n -o options | grep "ro,") ]; then
-			logger -t "$($basename $0)" FATAL: $FILE_SYSTEM is not mounted with ro option
-			echo $($basename $0): FATAL: $FILE_SYSTEM is not mounted with ro option
+			logger -t "$(basename $0)" FATAL: $FILE_SYSTEM is not mounted with ro option
+			echo $(basename $0): FATAL: $FILE_SYSTEM is not mounted with ro option
 			exit 1
 		fi
 	}
@@ -477,6 +478,6 @@ f_show_eligible_transcoding () {
 
 # Log the completion
 if [ ! $DEBUG_MODE ]; then
-	logger -t "$($basename $0)" Functions loaded from _functions
+	logger -t "$(basename $0)" Functions loaded from _functions
 	fi
 
