dbug

diff --git a/sbin/_functions b/sbin/_functions
--- a/sbin/_functions
+++ b/sbin/_functions
@@ -216,7 +216,9 @@ function f_move_one_file () {
 	if ! $(f_in_use "$IN_FILE"); then f_balk "$0: Skipped moving $IN_FILE because it's in use." false
 	if ! $(f_is_file "$IN_FILE"); then f_balk "$0: Cannot move non-existent file $IN_FILE." false
 	if ! $(f_is_directory "$ROOT_IN_PATH"); then f_balk "$0: Non-existent root in directory $ROOT_IN_PATH." false
+	}
 
+function f_fff () {
 	# Make the directory for out file
 	mkdir -p "$NEW_DIRECTORY"
 	if [ $? -ne 0 ]; then # If mkdir failed failed ...
@@ -228,11 +230,11 @@ function f_move_one_file () {
 	chmod 664 "$NEW_DIRECTORY"
 
 	# Move $IN_FILE to $OUT_FILE
-#	f_log_and_echo "$0: Moving $(basename \"$IN_FILE\")"
-#	if [ $? -ne 0 ]; then # If the move failed ...
-#		f_balk "$0: FAILED to move $IN_FILE to $NEW_DIRECTORY" false
-#	    sleep 10 # Add some time here in case we're racing through a failure loop.
-#		return
+	f_log_and_echo "$0: Moving $(basename \"$IN_FILE\")"
+	if [ $? -ne 0 ]; then # If the move failed ...
+		f_balk "$0: FAILED to move $IN_FILE to $NEW_DIRECTORY" false
+	    sleep 10 # Add some time here in case we're racing through a failure loop.
+		return
 	fi
   	chown plex:plex "$OUT_FILE"
 	chmod 664 "$OUT_FILE"
