dbug

diff --git a/sbin/_functions b/sbin/_functions
--- a/sbin/_functions
+++ b/sbin/_functions
@@ -204,14 +204,14 @@ function f_move_one_plex_file () {
 	SOURCE_FILE="$1"
 	TARGET_FILE="$2"
 
-	f_log_and_echo "$0: Moving '$SOURCE_FILE' to '$TARGET_FILE'" false
-	if ! $(f_is_file "$SOURCE_FILE");  then f_balk "$0: Directory not found: $1" false;     return; fi 
+	f_log_and_echo "$0: Moving $(basename '$SOURCE_FILE')" false
+	if ! $(f_is_file "$SOURCE_FILE");                   then f_balk "$0: Source file not found: $1" false;               return; fi 
 	mkdir -p $(dirname "$TARGET_FILE")
-	if ! $(f_is_directory "$(dirname '$TARGET_FILE')");  then f_balk "$0: Directory not found: $1" false;     return; fi 
+	if ! $(f_is_directory "$(dirname '$TARGET_FILE')"); then f_balk "$0: Target directory not found: $1" false;               return; fi 
 	chown plex:plex $(dirname "$TARGET_FILE")
 	chmod 775 $(dirname "$TARGET_FILE")
 	mv "$SOURCE_FILE" "$TARGET_FILE"
-	if [ $? -gt 0 ]; then f_balk "$0: Can't move '$SOURCE_FILE' to '$TARGET_FILE'"; return; fi
+	if [ $? -gt 0 ];										then f_balk "$0: Can't move '$SOURCE_FILE' to '$TARGET_FILE'"; return; fi
 	chown plex:plex "$TARGET_FILE"
 	chmod 664 "$TARGET_FILE"
 	}
@@ -223,9 +223,9 @@ function f_process_ts_file () {
 	STORE_ROOT_PATH="$3"
 	OUT_EXT="m4v"
 
-	if ! $(f_is_file "$IN_FILE");                      then f_balk "$0: File not found: $1" false;      return; fi 
-	if ! $(f_is_directory "$WORK_ROOT_PATH");          then f_balk "$0: Directory not found: $1" false; return; fi 
-	if ! $(f_is_directory "$STORE_ROOT_PATH");         then f_balk "$0: Directory not found: $1" false; return; fi 
+	if ! $(f_is_file "$IN_FILE");                      then f_balk "$0: TS file not found: $1" false;      return; fi 
+	if ! $(f_is_directory "$WORK_ROOT_PATH");          then f_balk "$0: Work directory not found: $1" false; return; fi 
+	if ! $(f_is_directory "$STORE_ROOT_PATH");         then f_balk "$0: Store directory not found: $1" false; return; fi 
 	if ! $(f_variable_has_content "$IGNORE_TV_SHOWS"); then f_balk "$0: TV filter undefined" false;     return; fi
 
 	WORK_ROOT_PATH_LENGTH=${#WORK_ROOT_PATH}
@@ -242,9 +242,9 @@ function f_process_ts_file () {
 	STORE_FILE="$STORE_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
 	STORE_FILE="$STORE_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
 
-	if ! $(f_variable_has_content "$OUT_FILE"); then f_balk "$0: Output file undefined" false; return; fi
+	if ! $(f_variable_has_content "$OUT_FILE");      then f_balk "$0: Output file undefined" false; return;   fi
 	if ! $(f_variable_has_content "$RELATIVE_FILE"); then f_balk "$0: Relative file undefined" false; return; fi
-	if ! $(f_variable_has_content "$STORE_FILE"); then f_balk "$0: Store file undefined" false; return; fi
+	if ! $(f_variable_has_content "$STORE_FILE");    then f_balk "$0: Store file undefined" false; return;    fi
 	if ! $(f_variable_has_content "$PLEX_LIVE_APPLICATION_SUPPORT"); then 
 		f_balk "$0: Plex live application support directory undefined" false; return; fi
 
@@ -265,12 +265,13 @@ function f_process_ts_file () {
 				f_balk "$HANDBRAKE_CLI: FAILED with $exit_status for $IN_FILE" true
 			else
 				rm "$IN_FILE" # Delete input file
-				logger $0: Transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))
+				f_log_and_echo "$0: Transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))" false
 			fi # End of check for transcoding failure
 		# Move all .m4v files from $VIDEO_WORK_DIRECTORY to $VIDEO_STORE_DIRECTORY.
-			find "$VIDEO_WORK_DIRECTORY" -type f -name "*.m4v" | while read M4V_FILE; do f_move_one_plex_file "$OUT_FILE" "$STORE_FILE"; done
-		echo "Sleeping 20 for diagnostics (so you can read any error messages that may appear above)."
-		sleep 20
+			find "$VIDEO_WORK_DIRECTORY" -type f -name "*.m4v" | while read M4V_FILE; do f_move_one_plex_file "$M4V_FILE" "$VIDEO_STORE_DIRECTORY/$M4V_FILE"; done
+		echo "Sleeping 120 for diagnostics (so you can read any error messages that may appear above)."
+		f_beep
+		sleep 120
 		fi
 	}
 
