upd

diff --git a/sbin/_functions b/sbin/_functions
--- a/sbin/_functions
+++ b/sbin/_functions
@@ -269,6 +269,7 @@ function f_process_ts_file () {
 		# "${PATHNAME[transcode_ripped_dvds]}" # Pick up ripped DVDs first, if any
 
 		# Do the transcoding
+		# yyy
 		TIMESTART=$(currenttimeinseconds)
 		IN_FILE_BASE=$(basename "$IN_FILE")
 		TEMP_ERRORS=false
@@ -418,28 +419,34 @@ function f_transcode_handbrake_source_video_file () {
 
 	if ! $(f_filter "$SOURCE_FILE" "$IGNORE_TV_SHOWS") || ! $USE_TV_FILTERS; then
 		
-	echo TARGET_FILE: $TARGET_FILE
-		# Do the transcoding
-		TIMESTART=$(currenttimeinseconds)
-		SOURCE_FILE_BASE=$(basename "$SOURCE_FILE")
-		f_log_and_echo "Transcoding $SOURCE_FILE_BASE to $TARGET_FILE" false
-		nice -19 "$HANDBRAKE_CLI" --preset-import-file "$HANDBRAKE_PRESETS" -i "$SOURCE_FILE" -o "$TARGET_FILE"
-		exit_status=$?
-		chown $RUN_AS:$RUN_AS "$TARGET_FILE"
-		chmod $DEFAULT_VIDEO_FILE_PERMISSIONS "$TARGET_FILE"
-		if $SET_PLEX_PERMISSIONS; then
-			chown $PLEX_USER:$PLEX_USER "$TARGET_FILE"
-			chmod $PLEX_VIDEO_FILE_PERMISSIONS "$TARGET_FILE"
-			fi
-		if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
-				f_balk "$HANDBRAKE_CLI: FAILED with $exit_status for $SOURCE_FILE" true
-			else
-				rm "$SOURCE_FILE" # Delete input file
-				f_log_and_echo "Transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))" false
-				echo
-			fi # End of check for transcoding failure
+	# Do the transcoding
+	TIMESTART=$(currenttimeinseconds)
+	SOURCE_FILE_BASE=$(basename "$SOURCE_FILE")
+	TEMP_ERRORS=false
+	TEMP_THIS_SCRIPT=$(basename "$0")
+	TEMP_ERROR_LOG="/tmp/Error Log for $HOSTNAME $TEMP_THIS_SCRIPT $(date) $(uuidgen)"
+	echo "$TEMP_ERROR_LOG" > "$TEMP_ERROR_LOG"
+	f_log_and_echo "Transcoding $SOURCE_FILE_BASE to $TARGET_FILE" false
+	nice -19 "$HANDBRAKE_CLI" --preset-import-file "$HANDBRAKE_PRESETS" -i "$SOURCE_FILE" -o "$TARGET_FILE"
+	exit_status=$?
+	chown $RUN_AS:$RUN_AS "$TARGET_FILE"
+	chmod $DEFAULT_VIDEO_FILE_PERMISSIONS "$TARGET_FILE"
+	if $SET_PLEX_PERMISSIONS; then
+		chown $PLEX_USER:$PLEX_USER "$TARGET_FILE"
+		chmod $PLEX_VIDEO_FILE_PERMISSIONS "$TARGET_FILE"
 		fi
-	}
+	if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
+			TEMP_ERRORS=true
+			echo "$HANDBRAKE_CLI: FAILED with $exit_status for $IN_FILE" >> "$TEMP_ERROR_LOG"				
+			f_balk "$HANDBRAKE_CLI: FAILED with $exit_status for $SOURCE_FILE" false
+			cat "$TEMP_ERROR_LOG" | mail -s "Error Log for $HOSTNAME $TEMP_THIS_SCRIPT" admin
+		else
+			rm "$SOURCE_FILE" # Delete input file
+			f_log_and_echo "Transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))" false
+			echo
+		fi # End of check for transcoding failure
+	fi
+}
 
 f_iterate_handbrake_source_video_files() {
 	# ONE pass through all matching source files, invoking f_transcode_handbrake_source_video_file for each
