dbug

diff --git a/sbin/_functions b/sbin/_functions
--- a/sbin/_functions
+++ b/sbin/_functions
@@ -276,24 +276,24 @@ function f_process_ts_file () {
 	# Hold this part out for now. Not sure this is the place for it.
 	# "${PATHNAME[transcode_ripped_dvds]}" # Pick up ripped DVDs first, if any
 
-	# Do the transcoding
-	TIMESTART=$(currenttimeinseconds)
-	IN_FILE_BASE=$(basename "$IN_FILE")
-	f_log_and_echo "$0: Transcoding $IN_FILE" false
-	nice "$HANDBRAKE_CLI" --preset-import-file "$HANDBRAKE_PRESETS" -i "$IN_FILE" -o "$OUT_FILE"
-	exit_status=$?
-	chown plex:plex "$OUT_FILE"
-	chmod 664 "$OUT_FILE"
-	if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
-			f_balk "$HANDBRAKE_CLI: FAILED with $exit_status for $IN_FILE" false
-		else
-			rm "$IN_FILE" # Delete input file
-			logger $0: Transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))
-		fi # End of check for transcoding failure
-	# Move all .m4v files from $VIDEO_WORK_DIRECTORY to $VIDEO_STORE_DIRECTORY.
-		find "$VIDEO_WORK_DIRECTORY" -type f -name "*.m4v" | while read M4V_FILE; 
-			do f_move_one_file "$M4V_FILE" "$VIDEO_WORK_DIRECTORY" "$VIDEO_STORE_DIRECTORY"; done
-	fi
+#	# Do the transcoding
+#	TIMESTART=$(currenttimeinseconds)
+#	IN_FILE_BASE=$(basename "$IN_FILE")
+#	f_log_and_echo "$0: Transcoding $IN_FILE" false
+#	nice "$HANDBRAKE_CLI" --preset-import-file "$HANDBRAKE_PRESETS" -i "$IN_FILE" -o "$OUT_FILE"
+#	exit_status=$?
+#	chown plex:plex "$OUT_FILE"
+#	chmod 664 "$OUT_FILE"
+#	if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
+#			f_balk "$HANDBRAKE_CLI: FAILED with $exit_status for $IN_FILE" false
+#		else
+#			rm "$IN_FILE" # Delete input file
+#			logger $0: Transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))
+#		fi # End of check for transcoding failure
+#	# Move all .m4v files from $VIDEO_WORK_DIRECTORY to $VIDEO_STORE_DIRECTORY.
+#		find "$VIDEO_WORK_DIRECTORY" -type f -name "*.m4v" | while read M4V_FILE; 
+#			do f_move_one_file "$M4V_FILE" "$VIDEO_WORK_DIRECTORY" "$VIDEO_STORE_DIRECTORY"; done
+#	fi
 
 
 
