upd

diff --git a/sbin/_functions b/sbin/_functions
--- a/sbin/_functions
+++ b/sbin/_functions
@@ -613,30 +613,25 @@ function f_transcode_file () {
 #		if [ "$SOURCE_FILE" != "$DIAG_SOURCE_FILE" ] ; then f_die "$SOURCE_FILE != $DIAG_SOURCE_FILE" true ; fi
 #		if ! $(f_is_file "$SOURCE_FILE"); then f_die "Source file (pt. 2) not found: $SOURCE_FILE" true; return; fi 
 #		echo "$TEMP_ERROR_LOG" > "$TEMP_ERROR_LOG"
-		f_log_and_echo "Transcoding $SOURCE_FILE to $TARGET_FILE" false
-		echo "$SOURCE_FILE" > /tmp/transcoding[$$]
-#		nice -19 "$HANDBRAKE_CLI" --preset-import-file "$HANDBRAKE_PRESETS" -i "$SOURCE_FILE" -o "$TARGET_FILE" > /dev/null 2>&1
-		"$HANDBRAKE_CLI" --preset-import-file "$HANDBRAKE_PRESETS" -i "$SOURCE_FILE" -o "$TARGET_FILE" > /dev/null 2>&1
-		exit_status=$? # 0 = No Error, 1 = Cancelled, 2 = Invalid Input, 3 = Initialization error, 4 = Unknown Error
-			# Exit code 139 seems to correspond to a "segmentation fault" that will cause a core dump and repeat every time the same source file is used for transcoding.
-		rm /tmp/transcoding[$$]
-		# chown $RUN_AS:$RUN_AS "$TARGET_FILE"
-		# chmod $DEFAULT_VIDEO_FILE_PERMISSIONS "$TARGET_FILE"
-#		if $SET_PLEX_PERMISSIONS; then
-#			chown $PLEX_USER:$PLEX_USER "$TARGET_FILE"
-#			chmod $PLEX_VIDEO_FILE_PERMISSIONS "$TARGET_FILE"
-#			fi
-		if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
-#				TEMP_ERRORS=true
-#				echo "HandBrakeCLI: FAILED with error #$exit_status for $SOURCE_FILE" >> "$TEMP_ERROR_LOG"				
-				f_balk "HandBrakeCLI: FAILED with error #$exit_status for $SOURCE_FILE" false
-				if [ $exit_status -eq 2 || $exit_status -eq 139 ] ; then rm "$SOURCE_FILE"; f_balk "Deleting corrupted file $SOURCE_FILE" false; fi
-			else
-				rm "$SOURCE_FILE" # Delete source file
-				f_log_and_echo "Transcoding complete in $(f_timeformat $(( $(date +%s) - TIMESTART )))" false
-				touch "$SUCCESSFUL_TRANSCODE_FLAG"
-				echo
-			fi # End of check for transcoding failure
+		if [ $(f_is_file "$SOURCE_FILE") && ! $(f_in_use "$SOURCE_FILE" false) ]; then
+			f_log_and_echo "Transcoding $SOURCE_FILE to $TARGET_FILE" false
+			echo "$SOURCE_FILE" > /tmp/transcoding[$$]
+			"$HANDBRAKE_CLI" --preset-import-file "$HANDBRAKE_PRESETS" -i "$SOURCE_FILE" -o "$TARGET_FILE" > /dev/null 2>&1
+			exit_status=$? # 0 = No Error, 1 = Cancelled, 2 = Invalid Input, 3 = Initialization error, 4 = Unknown Error
+				# Exit code 139 seems to correspond to a "segmentation fault" that will cause a core dump and repeat every time the same source file is used for transcoding.
+			rm /tmp/transcoding[$$]
+			# chown $RUN_AS:$RUN_AS "$TARGET_FILE"
+			# chmod $DEFAULT_VIDEO_FILE_PERMISSIONS "$TARGET_FILE"
+			if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
+					f_balk "HandBrakeCLI: FAILED with error #$exit_status for $SOURCE_FILE" false
+					if [ $exit_status -eq 2 || $exit_status -eq 139 ] ; then rm "$SOURCE_FILE"; f_balk "Deleting corrupted file $SOURCE_FILE" false; fi
+				else
+					rm "$SOURCE_FILE" # Delete source file
+					f_log_and_echo "Transcoding complete in $(f_timeformat $(( $(date +%s) - TIMESTART )))" false
+					touch "$SUCCESSFUL_TRANSCODE_FLAG"
+					echo
+				fi # End of check for transcoding failure
+			fi
 		fi
 	}
 
