dbug

diff --git a/sbin/_functions b/sbin/_functions
--- a/sbin/_functions
+++ b/sbin/_functions
@@ -20,7 +20,7 @@ function f_beep () {
 	}
 
 function f_balk () {
-	# Report and log the objection
+	# Report and log the objection; does NOT exit the program or function
 	# Usage: f_balk "$MESSAGE_TO_STDERR_AND_LOG" "SEND_TEXT_ALERT_TRUE_OR_FALSE"
 		f_log_and_echo "$1" "$2"
 		f_beep
@@ -205,15 +205,13 @@ function f_move_one_plex_file () {
 	TARGET_FILE="$2"
 
 	f_log_and_echo "$0: Moving '$SOURCE_FILE' to '$TARGET_FILE'" false
-	f_require_file "$SOURCE_FILE" true
+	if [ ! f_is_file "$SOURCE_FILE" ];  then f_balk "$0: Directory not found: $1" false;     return; fi 
 	mkdir -p $(dirname "$TARGET_FILE")
-	f_require_directory -p "$(dirname '$TARGET_FILE')" true
+	if [ ! f_is_directory "$(dirname '$TARGET_FILE')" ];  then f_balk "$0: Directory not found: $1" false;     return; fi 
 	chown plex:plex $(dirname "$TARGET_FILE")
 	chmod 775 $(dirname "$TARGET_FILE")
 	mv "$SOURCE_FILE" "$TARGET_FILE"
-	if [ $? -gt 0 ]; then
-		die "$0: FATAL: Can't move '$SOURCE_FILE' to '$TARGET_FILE'"
-		fi
+	if [ $? -gt 0 ]; then f_balk "$0: Can't move '$SOURCE_FILE' to '$TARGET_FILE'"; return; fi
 	chown plex:plex "$TARGET_FILE"
 	chmod 664 "$TARGET_FILE"
 	}
@@ -225,10 +223,10 @@ function f_process_ts_file () {
 	STORE_ROOT_PATH="$3"
 	OUT_EXT="m4v"
 
-	f_require_file "$IN_FILE" true
-	f_require_directory "$WORK_ROOT_PATH" true
-	f_require_directory "$STORE_ROOT_PATH" true
-	f_require_value "IGNORE_TV_SHOWS" "$IGNORE_TV_SHOWS" true
+	if [ ! f_is_file "$IN_FILE" ];                      then f_balk "$0: File not found: $1" false;      return; fi 
+	if [ ! f_is_directory "$WORK_ROOT_PATH" ];          then f_balk "$0: Directory not found: $1" false; return; fi 
+	if [ ! f_is_directory "$STORE_ROOT_PATH" ];         then f_balk "$0: Directory not found: $1" false; return; fi 
+	if [ ! f_variable_has_content "$IGNORE_TV_SHOWS" ]; then f_balk "$0: TV filter undefined" false;     return; fi
 
 	WORK_ROOT_PATH_LENGTH=${#WORK_ROOT_PATH}
 
@@ -244,10 +242,11 @@ function f_process_ts_file () {
 	STORE_FILE="$STORE_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
 	STORE_FILE="$STORE_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
 
-	f_require_value "OUT_FILE" "$OUT_FILE" true
-	f_require_value "RELATIVE_FILE" "$RELATIVE_FILE" true
-	f_require_value "STORE_FILE" "$STORE_FILE" true
-	f_require_value "plex_main_library_directory" "$PLEX_LIVE_APPLICATION_SUPPORT" true
+	if [ ! f_variable_has_content "$OUT_FILE" ]; then f_balk "$0: Output file undefined" false; return; fi
+	if [ ! f_variable_has_content "$RELATIVE_FILE" ]; then f_balk "$0: Relative file undefined" false; return; fi
+	if [ ! f_variable_has_content "$STORE_FILE" ]; then f_balk "$0: Store file undefined" false; return; fi
+	if [ ! f_variable_has_content "$PLEX_LIVE_APPLICATION_SUPPORT" ]; then 
+		f_balk "$0: Plex live application support directory undefined" false; return; fi
 
 	if ! $(f_filter "$IN_FILE" "$IGNORE_TV_SHOWS"); then
 		
@@ -270,8 +269,8 @@ function f_process_ts_file () {
 			fi # End of check for transcoding failure
 		# Move all .m4v files from $VIDEO_WORK_DIRECTORY to $VIDEO_STORE_DIRECTORY.
 			find "$VIDEO_WORK_DIRECTORY" -type f -name "*.m4v" | while read M4V_FILE; do f_move_one_plex_file "$OUT_FILE" "$STORE_FILE"; done
-		echo "Sleeping 60"
-		sleep 60
+		echo "Sleeping 20 for diagnostics (so you can read any error messages that may appear above)."
+		sleep 20
 		fi
 	}
 
