upd

diff --git a/sbin/_git b/sbin/_git
--- a/sbin/_git
+++ b/sbin/_git
@@ -29,6 +29,7 @@
 	source script-setup
 	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 61; fi
 	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 61; fi
+
 # Uncomment requirements for script execution
 	f_require_root
     # f_require_ubuntu
@@ -211,15 +212,19 @@ done
 	find $SERVICES_DIR -type f -print -exec chmod $SERVICES_FILE_PERMISSIONS {} \; >> /dev/null 2>&1
 
 ###################################################
-# DIAGNOSTIC CHECK.
-# Stopping program here to isolate a failure.
+# SAFE THROUGH THIS POINT.
 ###################################################
-    exit 1
 
 # Apply configs
     echo
     echo "Applying configurations"
 	f_apply_configs $ARGS
+
+###################################################
+# DIAGNOSTIC CHECK.
+###################################################
+    echo "Stopping program here to isolage a failure (_git)"
+    exit 1
 
 # # REMOVED THIS COMMAND 12/30/2020: Trying to isolate something that's killing all the systemd services on oz
 # # Reload systemd manager configuration
