upd

diff --git a/sbin/DisplayByteRangeInFile b/sbin/DisplayByteRangeInFile
--- a/sbin/DisplayByteRangeInFile
+++ b/sbin/DisplayByteRangeInFile
@@ -13,27 +13,49 @@ end_byte="$3"
 
 # CHECK FOR ENOUGH ARGUMENTS
 if [ $# -lt 3 ]; then
-    echo "Not enough arguments" >&2
+    echo "$(basename $0): Not enough arguments" >&2
+	echo "Usage: $(basename $0) file-to-search start-byte end-byte" >&2
     echo "Purpose: Displays a range of bytes in a file." >&2
     echo "First byte of the file is 1, not 0." >&2
-	echo "Usage: $(basename $0) file-to-search start-byte end-byte" >&2
 	exit 1
     fi
 
-if [ ! -f "$file" ]; then  # Check whether $file is not a regular file
-    echo "$file: File not found." >&2
+if [[ ! "$start_byte" =~ ^-?[0-9]+$ ]] || [ ! $start_byte -gt 0 ]; then
+    echo "$(basename $0): The start-byte must be an integer greater than zero." >&2
+	echo "Usage: $(basename $0) file-to-search start-byte end-byte" >&2
     echo "Purpose: Displays a range of bytes in a file." >&2
     echo "First byte of the file is 1, not 0." >&2
+	exit 22
+    fi
+
+if [[ ! "$end_byte" =~ ^-?[0-9]+$ ]] || [ ! $end_byte -gt 0 ]; then
+    echo "$(basename $0): The end-byte must be an integer greater than zero." >&2
 	echo "Usage: $(basename $0) file-to-search start-byte end-byte" >&2
+    echo "Purpose: Displays a range of bytes in a file." >&2
+    echo "First byte of the file is 1, not 0." >&2
+	exit 22
+    fi
+
+if [[ $end_byte -lt $start_byte ]]; then
+    echo "$(basename $0): The end-byte cannot be less than the start-byte." >&2
+ 	echo "Usage: $(basename $0) file-to-search start-byte end-byte" >&2
+    echo "Purpose: Displays a range of bytes in a file." >&2
+    echo "First byte of the file is 1, not 0." >&2
+	exit 22
+    fi
+
+if [ ! -f "$file" ]; then  # Check whether $file is not a regular file
+    echo "$(basename $0): $file: File not found." >&2
+    echo "Purpose: Displays a range of bytes in a file." >&2
+	echo "Usage: $(basename $0) file-to-search start-byte end-byte" >&2
+    echo "Purpose: Displays a range of bytes in a file." >&2
+    echo "First byte of the file is 1, not 0." >&2
     exit 169
     fi
 
 if $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
 
-count=$(($end_byte - $start_byte))
-skip=$(($start_byte - 1))
-
-dd if="$file" bs=1 skip=$skip count=$count 2>/dev/null
+tail -c+"$start_byte" "$file" | head -c+$(($end_byte-$start_byte))
 echo ""
 
 exit 0
diff --git a/sbin/DisplaySubstringInFile b/sbin/DisplaySubstringInFile
--- a/sbin/DisplaySubstringInFile
+++ b/sbin/DisplaySubstringInFile
@@ -13,29 +13,28 @@ first_exclude_text="$3"
 
 # CHECK FOR ENOUGH ARGUMENTS
 if [ $# -lt 3 ]; then
-    echo "Not enough arguments" >&2
+    echo "$(basename $0): Not enough arguments" >&2
+	echo "Usage: $(basename $0) file-to-search first-include-text first-exclude-text" >&2
     echo "Purpose: Displays a substring of a text file." >&2
-	echo "Usage: $(basename $0) first-include-text first-exclude-text" >&2
 	exit 1
     fi
 
 if [ ! -f "$file" ]; then  # Check whether $file is not a regular file
-    echo "$file: File not found." >&2
+    echo "$(basename $0): $file: File not found." >&2
+	echo "Usage: $(basename $0) file-to-search first-include-text first-exclude-text" >&2
     echo "Purpose: Displays a substring of a text file." >&2
-	echo "Usage: $(basename $0) first-include-text first-exclude-text" >&2
     exit 169
     fi
 
 if $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
 
 start_byte=$(FindTextInFile "$first_include_text" "$file")
-end_byte=$(FindTextInFile "$first_exclude_text" "$file")
-
-# echo "$file"
-# echo "$start_byte"
-# echo "$end_byte"
-# echo $(FindTextInFile "$first_include_text" "$file")
-# echo $(FindTextInFile "$first_exclude_text" "$file")
+end_byte=$(FindTextInFile "$first_exclude_text" "$file" "$start_byte")
+echo "$file"
+echo start_byte "$start_byte"
+echo end_byte "$end_byte"
+echo DisplayByteRangeInFile "$file" "$start_byte" "$end_byte"
+exit 1
 
 DisplayByteRangeInFile "$file" "$start_byte" "$end_byte"
 
diff --git a/sbin/FindTextInFile b/sbin/FindTextInFile
--- a/sbin/FindTextInFile
+++ b/sbin/FindTextInFile
@@ -12,26 +12,42 @@ field_number=1
 
 # CHECK FOR ENOUGH ARGUMENTS
 if [ $# -lt 2 ]; then
-    echo "Not enough arguments" >&2
+    echo "$(basename $0): Not enough arguments" >&2
+	echo "Usage: $(basename $0) string-to-find file-to-search [start-byte-number]" >&2
     echo "Purpose: Displays the byte position of the first instance of a string in a file." >&2
     echo "First byte of the file is 1, not 0." >&2
-	echo "Usage: $(basename $0) string-to-find file-to-search" >&2
 	exit 1
     fi
 
 if [ ! -f "$file" ]; then  # Check whether $file is not a regular file
-    echo "$file: File not found." >&2
+    echo "$(basename $0): $file: File not found." >&2
+	echo "Usage: $(basename $0) string-to-find file-to-search [start-byte-number]" >&2
     echo "Purpose: Displays the byte position of the first instance of a string in a file." >&2
     echo "First byte of the file is 1, not 0." >&2
-	echo "Usage: $(basename $0) string-to-find file-to-search" >&2
     exit 169
+    fi
+
+if [ $# -gt 2 ] ; then
+    if [[ ! "$3" =~ ^-?[0-9]+$ ]] || [ ! $3 -gt 0 ]; then
+        echo "$(basename $0): If specified, the start-byte-number must be an integer greater than zero." >&2
+        echo "Usage: $(basename $0) string-to-find file-to-search [start-byte-number]" >&2
+        echo "Purpose: Displays the byte position of the first instance of a string in a file." >&2
+        echo "First byte of the file is 1, not 0." >&2
+        exit 22
+        fi
     fi
 
 if $DEBUG_MODE ; then echo "DEBUG ENDING $0 line ${LINENO}" $(date +"%F %T.%3N %Z") ; fi
 
-grepresult=$(grep -abo "$search_string" "$file" | head -1)
-result=$(($(echo "$grepresult" | cut -d "$delimiter" -f "$field_number") + 1))
+start_byte=1
+if [ $# -gt 2 ]; then
+    if [ $3 -gt 0 ]; then
+        start_byte="$3"
+        fi
+    fi
+
+grepresult=$(tail -c+"$start_byte" "$file" | grep -abo "$search_string" | head -1 )
+result=$(($(echo "$grepresult" | cut -d "$delimiter" -f "$field_number") + "$start_byte" ))
 echo $result
 
 exit 0
-
