dbug

diff --git a/sbin/lgh b/sbin/lgh
--- a/sbin/lgh
+++ b/sbin/lgh
@@ -6,12 +6,55 @@
 	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
 	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi
 
-# Archive the cold backup
- 	if [ $COLD_BACKUP_FS_READ_ONLY ]; then f_mount_ro_fs_as_rw "$COLD_BACKUP_FILE_SYSTEM"; fi
- 	mkdir -p "$THIS_ARCHIVE_DIRECTORY"
- 	nice tar $BACKUP_OPTIONS $COLD_BACKUP_DIRECTORY
-	nice cp "$ARCHIVE_TAR_FULL_WEEKDAY3" "$ARCHIVE_TAR_FULL_MONTH"
- 	if [ $COLD_BACKUP_FS_READ_ONLY ]; then f_mount_ro_fs_as_ro "$COLD_BACKUP_FILE_SYSTEM" $COLD_BACKUP_FS_READ_ONLY; fi
+
+
+
+# Include script setup file
+	echo ${LINENO}
+	source script-setup
+	echo ${LINENO}
+	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; exit 1; fi
+	echo ${LINENO}
+	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; exit 1; fi
+	echo ${LINENO}
+
+if [ -z "$1" ]; then
+  echo "Usage: rip \"Title (year) [ movie | <minimum_number_of_seconds> ]\" &"
+  exit -1
+  fi
+echo ${LINENO}
+
+if [ -z "$2" ]; then
+    MINLENGTH=1200
+  else if [ "$2" == "movie" ]; then
+    MINLENGTH=4500
+    else MINLENGTH=$2
+    fi
+  fi
+echo ${LINENO}
+
+f_require_value "MakeMKV Program Path" "${PATHNAME[makemkvcon]}"
+echo ${LINENO}
+f_require_value "MakeMKV Output Directory" "$MAKEMKV_OUTPUT_DIRECTORY"
+echo ${LINENO}
+
+sudo -u $RUN_AS mkdir -p "$MAKEMKV_OUTPUT_DIRECTORY/$1"
+echo ${LINENO}
+f_require_directory "$MAKEMKV_OUTPUT_DIRECTORY/$1"
+echo ${LINENO}
+
+sudo -u $RUN_AS nice "${PATHNAME[makemkvcon]}" --minlength=$MINLENGTH mkv disc:0 all "$MAKEMKV_OUTPUT_DIRECTORY/$1"
+exit_status=$?
+f_beep
+eject
+if [ $exit_status -eq 0 ] ; then
+  echo "$1: Disk ripping completed successfully." | mail "$TEXT_ALERTS"
+  else echo "$1: Disk ripping FAILED. Code $exit_status" | mail "$TEXT_ALERTS"
+  fi
+
+
+
+
 
 # Include script footer file
 	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
