debug

diff --git a/sbin/lgh b/sbin/lgh
--- a/sbin/lgh
+++ b/sbin/lgh
@@ -1,8 +1,40 @@
 #!/bin/bash
-# lgh
-# Test Program
+# show-plex-ts-files
 
-echo $(/usr/local/sbin/tv-show-filter-status "KXAN News at 6")
-echo $(/usr/local/sbin/tv-show-filter-status "KTBS News at 5")
+production_mode=true
+debug_mode=false
+# debug_mode=true
+if $debug_mode ; then
+  set -x
+  fi
 
+logger "$0: Starting."
+
+# Make sure only root can run our script
+if [[ $EUID -ne 0 ]]; then
+  echo "This script must be run as root."
+  logger "$0: FAILED. This script must be run as root."
+  exit 1
+fi
+
+# Confirm that this host is oz
+if [[ $(hostname -s) != "oz" ]]; then
+  echo "This script can ony be run on server oz."
+  logger "$0: FAILED. This script can only be run on server oz."
+  exit 1
+fi
+
+WORK_ROOT="/mnt/ssd1tb/plex"
+COUNT_FILE="/tmp/one-dot-per-video-file-waiting-to-be-processed"
+
+find "$WORK_ROOT" -type f -name "*.ts" -print -printf "." >> $COUNT_FILE
+echo ""
+ps -ef | grep "HandBrake\|cskipper\|sleep\|shrink-plex-ts-files"
+echo ""
+df -Ht ext4
+echo ""
+
+echo "Files: $(wc -c $COUNT_FILE)"
+
+logger "$0: Ended without error."
 exit 0
