renaming from go and nuc01

diff --git a/sbin/make-seed-file b/sbin/make-seed-file
--- a/sbin/make-seed-file
+++ b/sbin/make-seed-file
@@ -32,10 +32,10 @@ if ! $(cp -r "$ADMIN_HOME_DIR/.ssh" "$TEMP_DIR/"); then
 	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
 	f_die "Failed copying ~/.ssh directory" false $?;
 	fi
-# echo "Copying /var/local/git/go/install/clean-setup and /var/local/git/go/install/variables"
-# if ! $(cp "/var/local/git/go/install/clean-setup" "/var/local/git/go/install/variables" "$TEMP_DIR/"); then
+# echo "Copying /var/local/git/ubuntu-tools/install/clean-setup and /var/local/git/ubuntu-tools/install/variables"
+# if ! $(cp "/var/local/git/ubuntu-tools/install/clean-setup" "/var/local/git/ubuntu-tools/install/variables" "$TEMP_DIR/"); then
 # 	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
-# 	f_die "Failed copying /var/local/git/go/install files" false $?;
+# 	f_die "Failed copying /var/local/git/ubuntu-tools/install files" false $?;
 # 	fi
 echo "Setting ownership for contents of '$TEMP_DIR'"
 if ! $(chown -R $ADMIN_USER:$ADMIN_USER "$TEMP_DIR"); then
@@ -75,7 +75,7 @@ echo "Success creating 'seeds.tar.gz.gpg'."
 echo "Attempting to email it to $ADMIN_EMAIL."
 echo "Here is your seed file:" | mail -A ./seeds.tar.gz.gpg -s "Seed file from $HOST_FQDN" lane@lanehensley.org
 echo "If the email doesn't reach you, download seeds.tar.gz.gpg with sftp."
-echo "  and add it to repository go/install/"
+echo "  and add it to repository ubuntu-tools/install/"
 
 # Include script footer file
 	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
