upd make-seed-file

diff --git a/sbin/make-seed-file b/sbin/make-seed-file
--- a/sbin/make-seed-file
+++ b/sbin/make-seed-file
@@ -40,11 +40,11 @@ if ! $(chown -R $ADMIN_USER:$ADMIN_USER "$TEMP_DIR"); then
 	f_die "Failed setting ownership for contents of '$TEMP_DIR'" false $?;
 	fi
 echo "Compressing '$TEMP_DIR' to '$SEED_TAR_FILE'"
-echo tar -czf "$SEED_TAR_FILE" -C "$TEMP_DIR" .git* .ssh
-tar -czf "$SEED_TAR_FILE" -C "$TEMP_DIR" .git* .ssh
-echo Exit Code $?
-exit 0
-if ! $(tar -cvzf "$SEED_TAR_FILE" -C "$TEMP_DIR" .git* .ssh); then
+echo tar -czf "$SEED_TAR_FILE" -C "$TEMP_DIR" .
+# tar -czf "$SEED_TAR_FILE" -C "$TEMP_DIR" .
+# echo Exit Code $?
+# exit 0
+if ! $(tar -czf "$SEED_TAR_FILE" -C "$TEMP_DIR" .); then
 	echo "Deleting '$TEMP_DIR'"
 	rm -r "$TEMP_DIR"
 	f_die "Failed creating '$SEED_TAR_FILE'" false $?;
