dbug

diff --git a/sbin/process-ts b/sbin/process-ts
--- a/sbin/process-ts
+++ b/sbin/process-ts
@@ -46,9 +46,9 @@ f_debug_variable "STORE_ROOT_PATH" "$STORE_ROOT_PATH"
 f_debug_variable "RELATIVE_FILE" "$RELATIVE_FILE"
 f_debug_variable "1" "$1"
 
-logger "$0: Transcoding $(basename $1)"
+# logger "$0: Transcoding $(basename $1)"
 
-sleep 30
+# sleep 30
 
 if $(f_filter "$IN_FILE" "${LANE_CONFIG[filter.transcode-excluded]}") ; then
     logger "$0: Skipped $IN_FILE"
@@ -56,23 +56,23 @@ else
     f_require_file "$IN_FILE"
     f_file_not_in_use "$IN_FILE"
 
-   logger "$0: started running /usr/local/sbin/transcode."
+#   logger "$0: started running /usr/local/sbin/transcode."
     ${LANE_CONFIG[script.transcode.pathname]} >> /dev/null 2>&1 # Pick up ripped DVDs first, if any
-   logger "$0: finished running /usr/local/sbin/transcode."
+#   logger "$0: finished running /usr/local/sbin/transcode."
 
     # Do the transcoding
     TIMESTART=$(currenttimeinseconds)
-    logger "$0: Transcoding $IN_FILE"
+    logger "$0: Transcoding $(basename $IN_FILE)"
     "${LANE_CONFIG[handbrake.program]}" --preset-import-file "${LANE_CONFIG[handbrake.presets]}" \
         -i "$IN_FILE" -o "$OUT_FILE" >> /dev/null 2>&1
     exit_status=$?
     if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
-        logger "${LANE_CONFIG[handbrake.program]}: FAILED with $exit_status for $IN_FILE"
-        echo "$(date) ${LANE_CONFIG[handbrake.program]}: FAILED with $exit_status for $RELATIVE_FILE" | mail -r "process-ts" lanecell
-        exit $exit_status
+            logger "${LANE_CONFIG[handbrake.program]}: FAILED with $exit_status for $IN_FILE"
+            echo "$(date) ${LANE_CONFIG[handbrake.program]}: FAILED with $exit_status for $RELATIVE_FILE" | mail -r "process-ts" lanecell
+            exit $exit_status
         else
-        rm "$IN_FILE" >> /dev/null 2>&1 # Delete input file
-        logger "${LANE_CONFIG[handbrake.program]}: transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART ))) for $OUT_FILE"
+            rm "$IN_FILE" >> /dev/null 2>&1 # Delete input file
+            logger "$0: transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))"
         fi # End of check for transcoding failure
 
     "${LANE_CONFIG[script.move-one-file.pathname]}" "$OUT_FILE" "$WORK_ROOT_PATH" "$STORE_ROOT_PATH"
