dbug

diff --git a/sbin/process-ts b/sbin/process-ts
--- a/sbin/process-ts
+++ b/sbin/process-ts
@@ -4,32 +4,28 @@
 # No final / on either path. For system root, use ""
 
 # Include script setup file
-logger $0 DEBUG negative E.1
-source $(dirname $0)/script-setup
-logger $0 DEBUG negative E.2
+	source script-setup
+	if [ ! $FUNCTIONS_ARE_DEFINED ]; then echo $0: Functions not defined. Aborting; logger $0: Functions not defined. Aborting; fi
+	if [ ! $VARIABLES_ARE_DEFINED ]; then echo $0: Variables not defined. Aborting; logger $0: Variables not defined. Aborting; fi
 
 IN_FILE="$1"
 WORK_ROOT_PATH="$2"
 STORE_ROOT_PATH="$3"
 
-sleep 60
-
-logger $0 DEBUG negative B.1
-f_require_config "filter.transcode-excluded"
-logger $0 DEBUG negative B.2
-f_require_file "${LANE_CONFIG[script.move-one-file.pathname]}"
-logger $0 DEBUG negative B.3
+f_require_file "IN_FILE"
+f_require_directory "$WORK_ROOT_PATH"
+f_require_directory "$STORE_ROOT_PATH"
+f_require_value "IGNORE_TV_SHOWS" $IGNORE_TV_SHOWS
+f_require_file "$PATHNAME[move_one_file]"
 
 OUT_EXT="m4v"
-FILTER_SCRIPT="/usr/local/sbin/tv-show-filter-status"
+
 
 WORK_ROOT_PATH_LENGTH=${#WORK_ROOT_PATH}
 
 IN_FILE_LENGTH=${#IN_FILE}
 IN_FILE_EXT="${IN_FILE##*.}"
 IN_FILE_EXT_LENGTH="${#IN_FILE_EXT}"
-
-logger $0 DEBUG negative B.4
 
 RELATIVE_FILE_LENGTH=$[IN_FILE_LENGTH-WORK_ROOT_PATH_LENGTH-1]
 RELATIVE_FILE=${IN_FILE: -$RELATIVE_FILE_LENGTH} # First remove WORK_ROOT_PATH
@@ -39,8 +35,6 @@ OUT_FILE="$WORK_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
 STORE_FILE="$STORE_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
 STORE_FILE="$STORE_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
 
-logger $0 DEBUG negative B.5
-
 # So here are useful variables defined ...
 # $IN_FILE
 # $OUT_FILE
@@ -48,6 +42,11 @@ logger $0 DEBUG negative B.5
 # $WORK_ROOT_PATH
 # $STORE_ROOT_PATH
 # $RELATIVE_FILE
+
+f_require_file "$OUT_FILE"
+f_require_value "RELATIVE_FILE" $RELATIVE_FILE
+f_require_value "STORE_FILE" $STORE_FILE
+f_require_value "plex_main_library_directory" "$PLEX_LIVE_APPLICATION_SUPPORT"
 
 f_debug_variable "IN_FILE" "$IN_FILE"
 f_debug_variable "OUT_FILE" "$OUT_FILE"
@@ -66,70 +65,54 @@ logger $0 DEBUG negative B.6
 # DEBUG
 # echo "$0 started." | mail lanecell
 
-logger $0 DEBUG C.1 $IN_FILE
-
-if $(f_filter "$IN_FILE" "${LANE_CONFIG[filter.transcode-excluded]}") ; then
-logger $0 DEBUG C.2
+if $(f_filter "$IN_FILE" "$IGNORE_TV_SHOWS) ; then
     logger $0: Skipped $IN_FILE
-logger $0 DEBUG C.3
 else
-logger $0 DEBUG C.4
-logger $0 DEBUG C.4.5 $IN_FILE
     f_file_not_in_use "$IN_FILE"
-logger $0 DEBUG C.5
 
-logger $0 DEBUG negative C
+    # Hold this part out for now. Not sure this is the place for it.
+    # "$PATHNAME[transcode_ripped_dvds]" # Pick up ripped DVDs first, if any
 
-#   logger "$0: started running /usr/local/sbin/transcode."
-    ${LANE_CONFIG[script.transcode-ripped-dvds.pathname]} >> /dev/null 2>&1 # Pick up ripped DVDs first, if any
-#   logger "$0: finished running /usr/local/sbin/transcode."
-
-logger $0 DEBUG negative B
     # Do the transcoding
     TIMESTART=$(currenttimeinseconds)
     IN_FILE_BASE=$(basename $IN_FILE)
-    logger "$0: DEBUG IN_FILE $IN_FILE"
     logger $0: Transcoding $IN_FILE_BASE
-    "${LANE_CONFIG[handbrake.program]}" --preset-import-file "${LANE_CONFIG[handbrake.presets]}" \
-        -i "$IN_FILE" -o "$OUT_FILE" >> /dev/null 2>&1
+    "$HANDBRAKE_CLI --preset-import-file $HANDBRAKE_PRESETS" -i "$IN_FILE" -o "$OUT_FILE"
     exit_status=$?
-logger $0 DEBUG negative A
     if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
-            logger "${LANE_CONFIG[handbrake.program]}: FAILED with $exit_status for $IN_FILE"
-            echo "$(date) ${LANE_CONFIG[handbrake.program]}: FAILED with $exit_status for $RELATIVE_FILE" | mail -r "process-ts" lanecell
+            logger "$HANDBRAKE_CLI: FAILED with $exit_status for $IN_FILE"
+            echo "$(date) $HANDBRAKE_CLI: FAILED with $exit_status for $IN_FILE" | mail $TEXT_ALERTS
             exit $exit_status
         else
-            rm "$IN_FILE" >> /dev/null 2>&1 # Delete input file
+            rm "$IN_FILE" # Delete input file
             logger $0: DEBUG: currenttimeinseconds $(currenttimeinseconds)
             logger $0: DEBUG: TIMESTART $TIMESTART
             logger $0: transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART )))
         fi # End of check for transcoding failure
 
-logger $0 DEBUG A
+    # Move all available .m4v files from WORK to STORE.
+    # DISABLE THIS FOR NOW.
+        # "$PATHNAME[move_one_file]" "$OUT_FILE" "$WORK_ROOT_PATH" "$STORE_ROOT_PATH"
+        # exit_status=$?
+        # if [ $exit_status -ne 0 ]; then # If the move failed ...
+        #         exit $exit_status
+        #     else
+        #         rm "$IN_FILE" # Delete input file
+        #     fi # End of check for transcoding failure
 
-    "${LANE_CONFIG[script.move-one-file.pathname]}" "$OUT_FILE" "$WORK_ROOT_PATH" "$STORE_ROOT_PATH"
-    exit_status=$?
-    if [ $exit_status -ne 0 ]; then # If the move failed ...
-            logger "${LANE_CONFIG[script.move-one-file.pathname]}: FAILED with $exit_status for $IN_FILE"
-            echo "$(date) ${LANE_CONFIG[script.move-one-file.pathname]}: FAILED with $exit_status for $RELATIVE_FILE" | mail -r "process-ts" lanecell
-            exit $exit_status
-        else
-            rm "$IN_FILE" >> /dev/null 2>&1 # Delete input file
-        fi # End of check for transcoding failure
     # Change permissions for Plex libraries
-        find /var/lib/plexmediaserver/Library -type d -print -exec chmod 775 {} \; >> /dev/null 2>&1
-        find /var/lib/plexmediaserver/Library -type f -print -exec chmod 664 {} \; >> /dev/null 2>&1
-        chown -R plex:plex /var/lib/plexmediaserver/Library
-	    find "$WORK_ROOT_PATH" -type d -print -exec chmod 775 {} \; >> /dev/null 2>&1
-	    find "$WORK_ROOT_PATH" -type f -print -exec chmod 664 {} \; >> /dev/null 2>&1
-	    find "$STORE_ROOT_PATH" -type d -print -exec chmod 775 {} \; >> /dev/null 2>&1
-	    find "$STORE_ROOT_PATH" -type f -print -exec chmod 664 {} \; >> /dev/null 2>&1
-        chown -R plex:plex "$WORK_ROOT_PATH"
-        chown -R plex:plex "$STORE_ROOT_PATH"
+        # Let's see if we have a problem before restoring this from comment. These are dangerous calls.
+        #    find "$PLEX_LIVE_APPLICATION_SUPPORT" -type d -print -exec chmod 775 {} \;
+        #    find "$PLEX_LIVE_APPLICATION_SUPPORT" -type f -print -exec chmod 664 {} \;
+        #    chown -R plex:plex /var/lib/plexmediaserver/Library
+	    #    find "$WORK_ROOT_PATH" -type d -print -exec chmod 775 {} \;
+	    #    find "$WORK_ROOT_PATH" -type f -print -exec chmod 664 {} \;
+	    #    find "$STORE_ROOT_PATH" -type d -print -exec chmod 775 {} \;
+	    #    find "$STORE_ROOT_PATH" -type f -print -exec chmod 664 {} \;
+        #    chown -R plex:plex "$WORK_ROOT_PATH"
+        #    chown -R plex:plex "$STORE_ROOT_PATH"
 fi
 
-logger $0 DEBUG B
-
 # Include script footer file
-f_debug_variable "script.script-footer.pathname" "${LANE_CONFIG[script.script-footer.pathname]}"
-source ${LANE_CONFIG[script.script-footer.pathname]}
+	f_debug_variable "script_footer" "${PATHNAME[script_footer]}"
+	source "${PATHNAME[script_footer]}"
