tv-show-filter-status

diff --git a/sbin/process-ts b/sbin/process-ts
--- a/sbin/process-ts
+++ b/sbin/process-ts
@@ -1,13 +1,7 @@
 #!/bin/bash
-# file-filter
-# Usage: file-filter <in|out> <test-string>
-# Takes a test string as a second argument or standard input.
-# For <in|out>=in
-#   If match found, <test-string> is echoed.
-#   If no match found, nothing is echoed.
-# For <in|out>=out
-#   If match found, nothing is echoed.
-#   If no match found, <test-string> is echoed.
+# process_ts
+# Usage: process_ts <input_file> <work_root_path> <store_root_path>
+# No final / on either path. For system root, use ""
 
 production_mode=true
 debug_mode=false
@@ -16,52 +10,42 @@ if $debug_mode ; then
   set -x
   fi
 
-# Copy command-line arguments over to new array
-ARGS=( $@ )
+IN_FILE=$1
+WORK_ROOT_PATH=$2
+STORE_ROOT_PATH=$3
 
-# Read in from piped input, if present, and append to newly-created array
-if [ ! -t 0 ]; then
-  readarray STDIN_ARGS < /dev/stdin
-  ARGS=( $@ ${STDIN_ARGS[@]} )
+OUT_EXT="m4v"
+
+WORK_ROOT_PATH_LENGTH=${#WORK_ROOT_PATH}
+
+IN_FILE_LENGTH=${#IN_FILE}
+IN_FILE_EXT="${IN_FILE##*.}"
+IN_FILE_EXT_LENGTH="${#IN_FILE_EXT}"
+
+RELATIVE_FILE_LENGTH=$[IN_FILE_LENGTH-WORK_ROOT_PATH_LENGTH-1]
+RELATIVE_FILE=${IN_FILE: -$RELATIVE_FILE_LENGTH} # First remove WORK_ROOT_PATH
+RELATIVE_FILE_NO_EXT_LENGTH=$[RELATIVE_FILE_LENGTH-IN_FILE_EXT_LENGTH-1] # Recalculate relative path length by removing extension length
+RELATIVE_FILE_NO_EXT=${RELATIVE_FILE:0:RELATIVE_FILE_NO_EXT_LENGTH} # Then remove IN_FILE_EXT
+
+OUT_FILE="$WORK_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
+STORE_FILE="$STORE_ROOT_PATH/$RELATIVE_FILE_NO_EXT.$OUT_EXT"
+
+HANDBRAKE="HandBrakeCLI"
+PRESET="/home/lhensley/.HandBrake/Lane 1080p (BluRay).json"
+
+# So here are useful variables defined ...
+# $IN_FILE
+# $OUT_FILE
+# $STORE_FILE
+# $WORK_ROOT_PATH
+# $STORE_ROOT_PATH
+# $RELATIVE_FILE
+
+# Make sure only root can run our script
+if [[ $EUID -ne 0 ]]; then
+  echo "This script must be run as root."
+  exit 1
 fi
-
-INITIAL_STATE=true
-
-# Single loop to process all arguments
-for ARG in "${ARGS[@]}"; do
-  if $INITIAL_STATE; then
-    MODE=$ARG
-  else
-    if [[ "$ARG" != *"ABC World News Tonight"* ]] \
-        && [[ "$ARG" != *"BBC World News"* ]] \
-        && [[ "$ARG" != *"CBS Evening News"* ]] \
-        && [[ "$ARG" != *"CBS Morning News"* ]] \
-        && [[ "$ARG" != *"CBS This Morning"* ]] \
-        && [[ "$ARG" != *"CBS Weekend News"* ]] \
-        && [[ "$ARG" != *"Face the Nation"* ]] \
-        && [[ "$ARG" != *"Jimmy Kimmel Live"* ]] \
-        && [[ "$ARG" != *"KXAN News"* ]] \
-        && [[ "$ARG" != *"Meet the Press"* ]] \
-        && [[ "$ARG" != *"NBC Nightly News"* ]] \
-        && [[ "$ARG" != *"Sunday Today"* ]] \
-        && [[ "$ARG" != *"The Late Show"* ]] \
-        && [[ "$ARG" != *"The Tonight Show"* ]] \
-        && [[ "$ARG" != *"Today (195"* ]] \
-        && [[ "$ARG" != *".grab"* ]]; then
-          if [ "$MODE" == "out" ]; then
-            echo $ARG
-            fi
-          else if [ "$MODE" == "in" ]; then
-            echo $ARG
-            fi
-      fi
-    fi
-INITIAL_STATE=false
-done
-
-echo $MODE
-exit 0
-
 
 if [[ "$IN_FILE" != *"ABC World News Tonight"* ]] \
     && [[ "$IN_FILE" != *"BBC World News"* ]] \
@@ -80,17 +64,29 @@ if [[ "$IN_FILE" != *"ABC World News Tonight"* ]] \
     && [[ "$IN_FILE" != *"Today (195"* ]] \
     && [[ "$IN_FILE" != *".grab"* ]]; then
 
-    sudo -u lhensley transcode >> /dev/null 2>&1 # Pick up ripped DVDs first, if any
+    # Make sure $IN_FILE exists
+    if [ ! -f "$IN_FILE" ]; then
+      logger "$0 no source file $IN_FILE"
+      exit 1
+      fi
+
+    # Make sure $IN_FILE is not in use
+    if [ -n "$(lsof "$IN_FILE" 2>/dev/null)" ]; then
+        logger "$0: File in use and cannot be processed: $IN_FILE"
+        exit 1
+      fi
+
+    transcode >> /dev/null 2>&1 # Pick up ripped DVDs first, if any
 
     # Do the transcoding
     TIMESTART=$(currenttimeinseconds)
     logger "$HANDBRAKE starting transcoding of $IN_FILE"
     $HANDBRAKE --preset-import-file "$PRESET" \
-        -i "$IN_FILE" -o "$OUT_FILE" >> /dev/null 2>&1
+        -i "$IN_FILE" -o "$OUT_FILE" | logger
     exit_status=$?
     if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
-        logger "$HANDBRAKE transcoding FAILED for $IN_FILE"
-        echo "Transcoding FAILED for $RELATIVE_FILE" | mail lanecell
+        logger "$HANDBRAKE transcoding FAILED with $exit_status for $IN_FILE"
+        echo "$(date) $0 Transcoding FAILED with $exit_status for $RELATIVE_FILE" | mail -r "process-ts" lanecell
         exit $exit_status
       else
         rm "$IN_FILE" >> /dev/null 2>&1 # Delete input file
