debug

diff --git a/sbin/process_ts b/sbin/process_ts
--- a/sbin/process_ts
+++ b/sbin/process_ts
@@ -47,6 +47,18 @@ if [[ $EUID -ne 0 ]]; then
   exit 1
 fi
 
+# Make sure $IN_FILE exists
+if [ ! -f "$IN_FILE" ]; then
+  logger "$0 no source file $IN_FILE"
+  exit 1
+  fi
+
+# Make sure $IN_FILE is not in use
+if [ -n "$(lsof "$IN_FILE" 2>/dev/null)" ]; then
+    logger "$0: File in use and cannot be processed: $IN_FILE"
+    exit 1
+  fi
+
 if [[ "$IN_FILE" != *"ABC World News Tonight"* ]] \
     && [[ "$IN_FILE" != *"BBC World News"* ]] \
     && [[ "$IN_FILE" != *"CBS Evening News"* ]] \
