debug

diff --git a/sbin/process_ts b/sbin/process_ts
--- a/sbin/process_ts
+++ b/sbin/process_ts
@@ -69,7 +69,7 @@ if [[ "$IN_PATH" != *"ABC World News Tonight"* ]] \
     # Do the transcoding
     TIMESTART=$(currenttimeinseconds)
     logger "$HANDBRAKE starting transcoding of $IN_PATH"
-    sudo -u plex $HANDBRAKE --preset-import-file "$PRESET" \
+    $HANDBRAKE --preset-import-file "$PRESET" \
         -i "$IN_PATH" -o "$OUT_PATH" >> /dev/null 2>&1
     exit_status=$?
     if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
@@ -80,9 +80,16 @@ if [[ "$IN_PATH" != *"ABC World News Tonight"* ]] \
         logger "$HANDBRAKE transcoding complete in $(timeformat $(( $(currenttimeinseconds) - TIMESTART ))) for $OUT_PATH"
       fi # End of check for transcoding failure
 
-    # Move the transcoded file to storage
+    # Make the directory for storage
     rm "$IN_PATH" >> /dev/null 2>&1
-    sudo -u plex mkdir -p "$(dirname $STORE_PATH)" >> /dev/null 2>&1 # Create the directory for the stored version
+    mkdir -p "$(dirname $STORE_PATH)" >> /dev/null 2>&1 # Create the directory for the stored version
+    exit_status=$?
+    if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
+        logger "$0 FAILED to make $(dirname $STORE_PATH)"
+        echo "Failed to make $(dirname $STORE_PATH)" | mail lanecell
+      fi
+
+    # Move the transcoded file to storage
     mv "$OUT_PATH" "$STORE_PATH" >> /dev/null 2>&1
     exit_status=$?
     if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
@@ -91,7 +98,7 @@ if [[ "$IN_PATH" != *"ABC World News Tonight"* ]] \
         exit $exit_status
       else
         logger "$0 moved $OUT_PATH to $(dirname $STORE_PATH)"
-      fi # End of check for transcoding failure
+      fi
 
     # Change permissions for Plex libraries
     if [ $HOST_NAME == "oz" ]; then
