dbug

diff --git a/sbin/script-setup b/sbin/script-setup
--- a/sbin/script-setup
+++ b/sbin/script-setup
@@ -8,6 +8,14 @@ function f_get-config () {
     /usr/local/sbin/get-config "$1" "$LANE_CONFIG_FILE_1" "$LANE_CONFIG_FILE_2"
     }
 
+function f_require_config {
+    if [ -z ${LANE_CONFIG[$1]} ]; then
+	    echo "$0: FATAL: Configuration not found: $1"
+	    logger "$0: FATAL: Configuration not found: $1"
+	    exit 1
+	    fi
+    }
+
 function f_require_file {
     if [ ! -f $1 ]; then
 	    echo "$0: FATAL: File not found: $1"
