upd

diff --git a/sbin/substr b/sbin/substr
--- a/sbin/substr
+++ b/sbin/substr
@@ -1,13 +1,31 @@
 #!/bin/bash
 # Based on https://superuser.com/questions/1001973/bash-find-string-index-position-of-substring
 
+MYNAME="Lane Hensley"
+MYEMAIL="lane@lanehensley.org"
+
+COMMANDNAME="substr"
+VERSION="0.1"
+COLOPHON="$MYNAME, $MYEMAIL"
+
 SEARCHSTRING="$1"
 FULLSTRING="$2"
+# FLAG="$3"
+
+if [ "$FULLSTRING" = "" ] ; then
+	echo "$COMMANDNAME v$VERSION"
+	echo "by $COLOPHON"
+	echo
+	echo "Usage: $0 STRING_SEARCHED_FOR STRING_SEARCHED"
+	echo "If the search fails, $COMMANDNAME returns -1."
+	echo "If the search succeeds, $COMMANDNAME returns the offset within STRING_SEARCHED " \
+	echo "  where STRING_SEARCHED_FOR is found."
+	exit -1
+	fi
 
 REMAINDER=${FULLSTRING#*$SEARCHSTRING}
-echo Returns $?
-echo $(( ${#FULLSTRING} - ${#REMAINDER} - ${#SEARCHSTRING} ))
-echo "$REMAINDER"
-
-exit 0
-
+OFFSET=$(( ${#FULLSTRING} - ${#REMAINDER} - ${#SEARCHSTRING} ))
+if $? ; then echo "Not found. Exit code is -1." ; exit -1 ; fi
+echo "Found at offset $OFFSET, and that is the exit code."
+# echo "Remainder: "'$REMAINDER'"
+exit $OFFSET
