debug

diff --git a/sbin/transcode b/sbin/transcode
--- a/sbin/transcode
+++ b/sbin/transcode
@@ -21,7 +21,7 @@ MAKEMKV_PROCESS=makemkvcon
 RSYNC_TARGET="lhensley@nuc01.lanehensley.org:/mnt/cloteal/Plex/uploads"
 
 if [ $(lh_is_running "$HANDBRAKE") == "true" ] ; then
-  echo "Transcode operation already running. Exiting."
+#  echo "Transcode operation already running. Exiting." 
   exit 1
 fi
 
@@ -31,18 +31,18 @@ mkdir -p "$M4V_PATH"
 PRODUCTIVE=true
 while [ $(lh_has_subdirectories "$MKV_BASE_PATH") == "true" ] \
     && [ $PRODUCTIVE == "true" ] ; do # Subdirs found under base
-  echo "  Found subdirectories under $MKV_BASE_PATH"
+#  echo "  Found subdirectories under $MKV_BASE_PATH"
   PRODUCTIVE=false
   for j in "$MKV_BASE_PATH/"*; do # For each subdirectory found under $MKV_BASE_PATH ...
     if [ -d "$j" ]; then # If if really is a subdirectory ...
-      echo "  Confirmed that $j is a subdirectory"
+#      echo "  Confirmed that $j is a subdirectory"
       for i in "$j/"*; do # For each file in that subdirectory ...
         if [ -f "$i" ]; then # If it really is a file ...
-          echo "  Recognize valid file: $i"
+#          echo "  Recognize valid file: $i"
           if [ -n "$(lsof "$i" 2>/dev/null)" ]; then # If source file IS in use and can't be processed ...
-            echo "  Source file \"$i\" is in use."
+#            echo "  Source file \"$i\" is in use."
           else # Source file is NOT in use, and ready to be processed.
-            echo "  Processing source file \"$i\"."
+#            echo "  Processing source file \"$i\"."
             let "VIDEOSTART = ${#MKV_BASE_PATH} + 2"
             let "VIDEOEND = ${#j}"
             VIDEONAME=$(echo $j | cut -c$VIDEOSTART-$VIDEOEND)
@@ -50,17 +50,17 @@ while [ $(lh_has_subdirectories "$MKV_BASE_PATH") == "true" ] \
             let "TITLEEND = ${#i} - 4"
             n=$(echo $i | cut -c$TITLESTART-$TITLEEND)
             VIDEONAME="$M4V_PATH/$VIDEONAME - $n.m4v"
-            echo "  Target pathname: $VIDEONAME"
+#            echo "  Target pathname: $VIDEONAME"
             if [ -f "$VIDEONAME" ]; then rm -Rf "$VIDEONAME"; fi
             $HANDBRAKE --preset-import-file "$PRESET" \
-              -i "$i" -o "$VIDEONAME"
+              -i "$i" -o "$VIDEONAME"  >> /dev/null 2>&1
             exit_status=$?
             if [ $exit_status -ne 0 ]; then # If the transcoding failed ...
-              echo "    Transcoding of \"$i\" failed with error code $exit_status."
+#              echo "    Transcoding of \"$i\" failed with error code $exit_status."
               echo "Transcoding to $VIDEONAME FAILED." | mail lanecell
               echo "$HANDBRAKE transcoded title $n returned error number $exit_status." | mail lanecell
             else
-              rm "$i" # Delete source file
+              rm "$i" # Delete source file >> /dev/null 2>&1
               PRODUCTIVE=true
               echo "Transcoding to $VIDEONAME successful." | mail lanecell
               fi # End of check for transcoding failure
@@ -69,20 +69,25 @@ while [ $(lh_has_subdirectories "$MKV_BASE_PATH") == "true" ] \
           if find "$j" -mindepth 1 -print -quit 2>/dev/null | grep -q .; then # If more files in subdirectory ...
             sleep 1 # Do nothing ...
           else
-            rm -Rf "$j" # Delete source subdirectory
+            rm -Rf "$j" >> /dev/null 2>&1 # Delete source subdirectory
             fi # End of check for more files in source subdirectory
         done # Next file in the subdirectory ...
       fi # End of check to confirm that there are any files in the subdirectory
     done # Next subdirectory under $MKV_BASE_PATH (iterating through them)
   done # End of check to confirm that this are any subdirectories under $MKS_BASE_PATH
 
-chown plex:plex $M4V_PATH/*
-sudo -u lhensley rsync -rvE $M4V_PATH/ $RSYNC_TARGET
-exit_status=$?
-if [ $exit_status -eq 0 ] ; then
-  rm $M4V_PATH/*
-  fi
+if $PRODUCTIVE; then
+    chown plex:plex $M4V_PATH/*
+    echo "Uploading to nuc01" | mail lanecell
+    sudo -u lhensley rsync -rvE $M4V_PATH/ $RSYNC_TARGET
+    echo "Upload done."
+    exit_status=$?
+    if [ $exit_status -eq 0 ] ; then
+      rm $M4V_PATH/* >> /dev/null 2>&1
+      fi
 
-echo "Transcoding is complete." | mail lanecell
-echo Done.
+    # echo "Transcoding is complete." | mail lanecell
+    # echo Done.
+fi
+
 exit 0
