debug

diff --git a/sbin/setup/install-virtual-host b/sbin/setup/install-virtual-host
--- a/sbin/setup/install-virtual-host
+++ b/sbin/setup/install-virtual-host
@@ -1,17 +1,5 @@
 #!/bin/bash
-# install-apache2-site
-# Options: install-apache2-site [options] FQDN
-#    -a    Apache2 Configs Directory (default: /etc/apache2)
-#    -c    Certificate Config Directory (default: /etc/letsencrypt)
-#    -d    Document Root Container Directory (default: /var/www)
-#    -e    Error log file (default: /var/log/apache2/error.log)
-#    -f    Custom log file (default: /var/log/apache2/access.log)
-#    -l    Live Certificate Config Directory (default: "live" in directory specified with -c)
-#    -p    MySQL Password; only needed if WordPress is being installed
-#    -u    MySQL User Name; only needed if WordPress is being installed
-#    -w    Web Admin User's Full Name (default: "Lane Hensley")
-#    -x    Web Admin User's Email Address (default "lane.hensley@alumni.duke.edu")
-#    -z    Remove the Site
+# install-virtual-host
 
 # DEFINE THESE VARIABLES BEFORE RUNNING THE SCRIPT!
 # fqdn='domain.tld'
@@ -20,7 +8,7 @@ web_admin_email='lane.hensley@alumni.duke.edu'
 remove=false
 mysql_root_user=''
 mysql_root_password=''
-script_name=install-apache2-site
+script_name=$0
 current_directory=$(pwd)
 docroot_base="/var/www"
 apache2_configs="/etc/apache2"
@@ -29,6 +17,7 @@ custom_log="/var/log/apache2/access.log"
 certificate_conf_dir="/etc/letsencrypt"
 certificate_live_dir="live"
 excluded_password_characters="\";\$\`\!\*\@"
+install_wordpress=false
 
 debug_mode=false
 #debug_mode=true
@@ -36,27 +25,28 @@ if $debug_mode ; then
   set -x
   fi
 
-function backout {
-  echo "Backing out the installation."
+# Abort and exit
+function abort_and_exit {
   cd $current_directory
-  rm -f -r $docroot
-  rm -f $site_enabled
-  rm -f $site_conf
-  query="DROP DATABASE IF EXISTS \`wp_$fqdn\`; DROP USER IF EXISTS 'wp_$fqdn'@'localhost'; FLUSH PRIVILEGES;"
-#  mysql -u $mysql_root_user -p$mysql_root_password -e "$query" > /dev/null 2> /dev/null
-  mysql -u $mysql_root_user -p$mysql_root_password -e "$query" > /dev/null 2> /dev/null
-  systemctl restart apache2
+  echo "Aborted."
+  exit 1
+  }
+
+# Clean exit
+function clean_exit {
+  cd $current_directory
+  exit 0
   }
 
 # Make sure only root can run our script
 if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root." 1>&2
-  echo "Aborted."
-  exit 1
+  abort_and_exit
   fi
 
 function print_usage {
-  echo "Usage: install-apache2-site [options] FQDN"
+  echo "Usage: $script_name [options] fully-qualified-domain-name"
+  echo "Options:"
   echo "  -a    Apache2 Configs Directory (default: /etc/apache2)"
   echo "  -c    Certificate Config Directory (default: /etc/letsencrypt)"
   echo "  -d    Document Root Container Directory (default: /var/www)"
@@ -67,12 +57,17 @@ function print_usage {
   echo "  -p    MySQL Password; only needed if WordPress is being installed"
   echo "  -u    MySQL User Name; only needed if WordPress is being installed"
   echo "  -w    Web Admin User's Full Name (default: \"Lane Hensley\")"
+  echo "  -W    Install WordPress"
   echo "  -x    Web Admin User's Email Address (default \"lane.hensley@alumni.duke.edu\")"
-  echo "  -z    Remove/uninstall the Site"
+  echo "  -X    Remove/uninstall the virtual host"
+  echo "Example installation with WordPress:     $script_name -W -u MYSQL_USER -p MYSQL_PASSWORD FQDN"
+  echo "Example installation without WordPress:  $script_name FQDN"
+  echo "Example removal including WordPress:     $script_name -X -W -u MYSQL_USER -p MYSQL_PASSWORD FQDN"
+  echo "Example removal without WordPress:       $script_name -X FQDN"
 }
 
 # Following tutorial at https://sookocheff.com/post/bash/parsing-bash-script-arguments-with-shopts/
-while getopts ":a:c:d:e:f:hl:p:u:w:x:z" opt; do
+while getopts ":a:c:d:e:f:hl:p:u:w:Wx:X" opt; do
     case ${opt} in
       a )  apache2_configs=$OPTARG
            ;;
@@ -85,7 +80,7 @@ while getopts ":a:c:d:e:f:hl:p:u:w:x:z" opt; do
       f )  custom_log=$OPTARG
            ;;
       h )  print_usage
-           exit 0
+           clean_exit
            ;;
       l )  certificate_live_dir=$OPTARG
            ;;
@@ -95,9 +90,11 @@ while getopts ":a:c:d:e:f:hl:p:u:w:x:z" opt; do
            ;;
       w )  web_admin_user=$OPTARG
            ;;
+      W )  install_wordpress=true
+           ;;
       x )  web_admin_email=$OPTARG
            ;;
-      z )  remove=true
+      X )  remove=true
            ;;
       \? ) print_usage
            ;;
@@ -113,50 +110,56 @@ docroot=$docroot_base/$fqdn
 site_conf=$apache2_configs/sites-available/$fqdn.conf
 site_enabled=$apache2_configs/sites-enabled/$fqdn.conf
 
-echo "basename:                      $(basename $0)"
-echo "fqdn:                          $fqdn"
-echo "docroot:                       $docroot"
-echo "site_conf:                     $site_conf"
-echo "site_enabled:                  $site_enabled"
-echo "web_admin_user:                $web_admin_user"
-echo "web_admin_email:               $web_admin_email"
-echo "remove:                        $remove"
-echo "mysql_root_user:               $mysql_root_user"
-echo "mysql_root_password:           $mysql_root_password"
-echo "script_name:                   $script_name"
-echo "current_directory:             $current_directory"
-echo "docroot_base:                  $docroot_base"
-echo "apache2_configs:               $apache2_configs"
-echo "error_log:                     $error_log"
-echo "custom_log:                    $custom_log"
-echo "certificate_conf_dir:          $certificate_conf_dir"
-echo "certificate_live_dir:          $certificate_live_dir"
-echo "excluded_password_characters:  $excluded_password_characters"
+# Backout the installation
+function backout {
+  echo "Backing out the installation."
+  if $install_wordpress ; then
+      echo "WordPress admin password tried: $admin_wp_pwd"
+      echo "MySQL password for WordPress database on user 'wp_$fqdn'@'localhost' tried: $admin_wp_pwd"
+    fi
+  cd $current_directory
+  rm -f -r $docroot
+  rm -f $site_enabled
+  rm -f $site_conf
+  query="DROP DATABASE IF EXISTS \`wp_$fqdn\`; DROP USER IF EXISTS 'wp_$fqdn'@'localhost'; FLUSH PRIVILEGES;"
+#  mysql -u $mysql_root_user -p$mysql_root_password -e "$query" > /dev/null 2> /dev/null
+  mysql -u $mysql_root_user -p$mysql_root_password -e "$query" > /dev/null 2> /dev/null
+  systemctl restart apache2
+  systemctl restart mysql
+  }
 
-exit -1
-
-
+# Check that $fqdn exists and is well-formed
+result=`echo $fqdn | grep -P '(?=^.{1,254}$)(^(?>(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)'`
+if [[ "$result" == "" ]]
+then
+    echo "Fully qualified domain name is not given."
+    abort_and_exit
+fi
+if [[ -z "$result" ]]
+then
+    echo "$fqdn is NOT a fully qualified domain name."
+    abort_and_exit
+fi
 
 # Check for removal option
 if $remove ; then
   backout
   echo "$fqdn virtual server removed."
-  exit 0
+  clean_exit
   fi
 
 # Check that target directory does not contain files; create it if needed.
 if [ -d "$docroot" ]; then # If docroot already exists
   if ! [ -z "$(ls -A $docroot)" ]; then # If docroot is not empty
     echo "$docroot is not empty."
-    echo "Aborted."
-    exit 1
+    abort_and_exit
     fi
   else
     mkdir $docroot
   fi
 
 # Do updates and install needed tools
-apt-get update && apt -y dist-upgrade && apt -y clean && apt -y autoremove
+_run_apt_updates
 # For Ubuntu 18
 # apt-get install -y wget apg certbot python python-certbot-apache
 # For Ubuntu 18
@@ -166,83 +169,81 @@ apt-get install -y wget apg certbot python3-certbot-apache
 admin_wp_pwd="$(apg -a 1 -m 20 -n 1 -MCLNS)"
 mysql_wp_pwd="$(apg -a 1 -m 20 -n 1 -MCLNS)"
 
-# Add MySQL database and user
-query="DROP USER IF EXISTS 'wp_$fqdn'@'localhost'; FLUSH PRIVILEGES; CREATE USER 'wp_$fqdn'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$mysql_wp_pwd';GRANT USAGE ON *.* TO 'wp_$fqdn'@'localhost';ALTER USER 'wp_$fqdn'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS \`wp_$fqdn\`;GRANT ALL PRIVILEGES ON \`wp_$fqdn\`.* TO 'wp_$fqdn'@'localhost';"
-# if ! mysql -u $mysql_root_user -p'$mysql_root_password' -e "$query" > /dev/null 2> /dev/null; then
-if ! mysql -u $mysql_root_user -p$mysql_root_password -e "$query"; then
-  backout
-  echo "Could not add MySQL database and user."
-  echo "Aborted."
-  exit 1
-  fi
-
 # Move to docroot
 if ! cd "$docroot"; then
   backout
-  echo "Could not move to $docroot."
-  echo "Aborted."
-  exit 1
+  echo "Could not change directory to $docroot."
+  abort_and_exit
   fi
 
+# Add MySQL database and user for WordPress
+if $install_wordpress ; then
+    query="DROP USER IF EXISTS 'wp_$fqdn'@'localhost'; FLUSH PRIVILEGES; CREATE USER 'wp_$fqdn'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$mysql_wp_pwd';GRANT USAGE ON *.* TO 'wp_$fqdn'@'localhost';ALTER USER 'wp_$fqdn'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS \`wp_$fqdn\`;GRANT ALL PRIVILEGES ON \`wp_$fqdn\`.* TO 'wp_$fqdn'@'localhost';"
+    # if ! mysql -u $mysql_root_user -p'$mysql_root_password' -e "$query" > /dev/null 2> /dev/null; then
+    if ! mysql -u $mysql_root_user -p$mysql_root_password -e "$query"; then
+      backout
+      echo "Could not add MySQL database and user."
+      abort_and_exit
+      fi
+    fi
+
 # Install wordpress
-if ! wget https://wordpress.org/latest.tar.gz; then
-  backout
-  echo "Could not download Wordpress."
-  echo "Aborted."
-  exit 1
-  fi
-if ! tar xzf latest.tar.gz; then
-  backout
-  echo "Could not unpack latest.tar.gz in $docroot."
-  echo "Aborted."
-  exit 1
-  fi
-if ! mv wordpress/* .; then
-  backout
-  echo "Could not move wordpress directory contents into $docroot."
-  echo "Aborted."
-  exit 1
+if $install_wordpress ; then
+    if ! wget https://wordpress.org/latest.tar.gz; then
+      backout
+      echo "Could not download Wordpress."
+      abort_and_exit
+      fi
+    if ! tar xzf latest.tar.gz; then
+      backout
+      echo "Could not unpack latest.tar.gz in $docroot."
+      abort_and_exit
+      fi
+    if ! mv wordpress/* .; then
+      backout
+      echo "Could not move wordpress directory contents into $docroot."
+      abort_and_exit
+      fi
   fi
 
 # Clean up
-rmdir wordpress
-rm latest.tar.gz
+rmdir -rf wordpress
+rm -f latest.tar.gz
 chown -R www-data:www-data .
 
 # Append to wp-includes/functions.php to increase max upload size
-if ! echo "@ini_set( 'upload_max_size' , '2G' );" >> $docroot/wp-includes/functions.php; then
-  backout
-  echo "Could not append to $docroot/wp-includes/functions.php."
-  echo "Aborted."
-  exit 1
-  fi
-if ! echo "@ini_set( 'post_max_size', '2G' );" >> $docroot/wp-includes/functions.php; then
-  backout
-  echo "Could not append to $docroot/wp-includes/functions.php."
-  echo "Aborted."
-  exit 1
-  fi
-if ! echo "@ini_set( 'max_execution_time', '300' );" >> $docroot/wp-includes/functions.php; then
-  backout
-  echo "Could not append to $docroot/wp-includes/functions.php."
-  echo "Aborted."
-  exit 1
+if $install_wordpress ; then
+    if ! echo "@ini_set( 'upload_max_size' , '2G' );" >> $docroot/wp-includes/functions.php; then
+      backout
+      echo "Could not append to $docroot/wp-includes/functions.php."
+      abort_and_exit
+      fi
+    if ! echo "@ini_set( 'post_max_size', '2G' );" >> $docroot/wp-includes/functions.php; then
+      backout
+      echo "Could not append to $docroot/wp-includes/functions.php."
+      abort_and_exit
+      fi
+    if ! echo "@ini_set( 'max_execution_time', '300' );" >> $docroot/wp-includes/functions.php; then
+      backout
+      echo "Could not append to $docroot/wp-includes/functions.php."
+      abort_and_exit
+      fi
   fi
 
 # Create php.ini in docroot
-if ! echo "upload_max_filesize = 2G" > $docroot/php.ini; then
-  backout
-  echo "Could not create $docroot/php.ini."
-  echo "Aborted."
-  exit 1
-  fi
-echo "post_max_size = 2G" >> $docroot/php.ini
-echo "max_execution_time = 300" >> $docroot/php.ini
-if ! chown www-data:www-data $docroot/php.ini; then
-  backout
-  echo "Could not set ownership for $docroot/php.ini."
-  echo "Aborted."
-  exit 1
+if $install_wordpress ; then
+    if ! echo "upload_max_filesize = 2G" > $docroot/php.ini; then
+      backout
+      echo "Could not create $docroot/php.ini."
+      abort_and_exit
+      fi
+    echo "post_max_size = 2G" >> $docroot/php.ini
+    echo "max_execution_time = 300" >> $docroot/php.ini
+    if ! chown www-data:www-data $docroot/php.ini; then
+      backout
+      echo "Could not set ownership for $docroot/php.ini."
+      abort_and_exit
+      fi
   fi
 
 # Install SSL certificate.
@@ -257,8 +258,7 @@ if ! certbot certonly --apache -d $fqdn; then
 if ! echo "<VirtualHost *:443>" > $site_conf; then
   backout
   echo "Could not create $site_conf."
-  echo "Aborted."
-  exit 1
+  abort_and_exit
   fi
 echo "DocumentRoot \"$docroot\"" >> $site_conf
 echo "ServerAdmin $web_admin_email" >> $site_conf
@@ -303,8 +303,7 @@ chmod 644 $site_conf
 if ! ln -s $site_conf $site_enabled; then
   backout
   echo "Could not enable virtual host $fqdn."
-  echo "Aborted."
-  exit 1
+  abort_and_exit
   fi
 chown root:root $site_enabled
 
@@ -317,15 +316,13 @@ if ! systemctl status apache2 > /dev/null ; then
   if ! systemctl restart apache2; then
     backout
     echo "Error restarting apache2."
-    echo "Aborted."
-    exit 1
+    abort_and_exit
   else
     backout
     echo "Apache2 will not start with virtual host $fqdn defined."
     echo "Virtual host $fqdn has been deleted."
     echo "Apache2 is running."
-    echo "Aborted."
-    exit 1
+    abort_and_exit
     fi
   fi
 
@@ -342,24 +339,31 @@ if ! certbot --apache -d $fqdn; then
   fi
 
 # Append to .htaccess to increase max upload size
-echo "php_value upload_max_filesize 2G" >> $docroot/.htaccess
-echo "php_value post_max_size 2G" >> $docroot/.htaccess
-echo "php_value memory_limit 256M" >> $docroot/.htaccess
-echo "php_value max_execution_time 300" >> $docroot/.htaccess
-echo "php_value max_input_time 300" >> $docroot/.htaccess
+if $install_wordpress ; then
+    echo "php_value upload_max_filesize 2G" >> $docroot/.htaccess
+    echo "php_value post_max_size 2G" >> $docroot/.htaccess
+    echo "php_value memory_limit 256M" >> $docroot/.htaccess
+    echo "php_value max_execution_time 300" >> $docroot/.htaccess
+    echo "php_value max_input_time 300" >> $docroot/.htaccess
+  fi
 
 # Apply proper permissions to .htaccess
 chown www-data:www-data $docroot/.htaccess
 chmod 644 $docroot/.htaccess
 
 # Report results to end user
-echo "IMPORTANT: COPY THIS INFORMATION NOW."
-echo "  Virtual host URL: https://$fqdn"
-echo "  MySQL database name: wp_$fqdn"
-echo "  MySQL user name: wp_$fqdn"
-echo "  MySQL password for $fqdn database: $mysql_wp_pwd"
-echo "  WordPress administrator user name: $web_admin_user"
-echo "  WordPress administrator password: $admin_wp_pwd"
-echo "  WordPress administrator email: $web_admin_email"
+if $install_wordpress ; then
+    echo "IMPORTANT: COPY THIS INFORMATION NOW."
+    echo "  Virtual host URL: https://$fqdn"
+    echo "  MySQL database name: wp_$fqdn"
+    echo "  MySQL user name: wp_$fqdn"
+    echo "  MySQL password for $fqdn database: $mysql_wp_pwd"
+    echo "  WordPress administrator user name: $web_admin_user"
+    echo "  WordPress administrator password: $admin_wp_pwd"
+    echo "  WordPress administrator email: $web_admin_email"
+  fi
+
+# All done.
 echo "  SSL certificate for $fqdn $certificate_successfully_installed installed."
-exit 0
+clean_exit
+
