upd make-seed-file umpstart etc

diff --git a/install/jumpstart b/install/jumpstart
--- a/install/jumpstart
+++ b/install/jumpstart
@@ -1,26 +1,44 @@
 #!/bin/bash
 
-echo
-echo sudo apt-get update && sudo apt-get dist-upgrade
-sudo apt-get update && sudo apt-get dist-upgrade
+if [[ $EUID -ne 0 ]]; then
+	# echo "You are not using root credentials."
+	echo "Root privileges required."
+	exit 1
+	fi
 
 echo
-echo sudo apt-get -y install coreutils git gpg moreutils '\'
+echo apt-get update && sudo apt-get dist-upgrade
+apt-get update && sudo apt-get dist-upgrade
+
+echo
+echo apt-get -y install coreutils git gpg moreutils '\'
 echo "   " openssh-client openssh-server ufw util-linux
-sudo apt-get -y install coreutils git gpg moreutils \
+apt-get -y install coreutils git gpg moreutils \
 	openssh-client openssh-server ufw util-linux
 
 echo
-echo wget --no-cache https://github.com/lhensley/go/raw/master/install/seeds.tar.gz.gpg
-wget --no-cache https://github.com/lhensley/go/raw/master/install/seeds.tar.gz.gpg
+echo wget --no-cache -O seeds.tar.gz.gpg https://github.com/lhensley/go/raw/master/install/seeds.tar.gz.gpg
+wget --no-cache -O seeds.tar.gz.gpg https://github.com/lhensley/go/raw/master/install/seeds.tar.gz.gpg
+
+echo
+echo wget --no-cache -O clean-setup https://github.com/lhensley/go/raw/master/install/clean-setup
+wget --no-cache -O clean-setup https://github.com/lhensley/go/raw/master/install/clean-setup
+
+echo
+echo wget --no-cache -O variables https://github.com/lhensley/go/raw/master/install/variables
+wget --no-cache -O variables https://github.com/lhensley/go/raw/master/install/variables
 
 echo
 echo gpg -d -o seeds.tar.gz seeds.tar.gz.gpg "# Password in 1Password; search \"seed\""
 gpg -d -o seeds.tar.gz seeds.tar.gz.gpg # Password in 1Password; search "seed"
 
 echo
-echo sudo chmod 600 seeds.tar.gz
-sudo chmod 600 seeds.tar.gz
+echo chmod 600 seeds.tar.gz
+chmod 600 seeds.tar.gzw
+
+echo
+echo chmod 600 seeds.tar.gz
+chmod 600 seeds.tar.gz
 
 echo
 echo tar -xvzf ./seeds.tar.gz
@@ -29,6 +47,15 @@ tar -xvzf ./seeds.tar.gz
 echo
 echo chmod 700 ./clean-setup && sudo ./clean-setup
 chmod 700 ./clean-setup && sudo ./clean-setup
+
+echo
+echo chown -R $SUDO_USER:$SUDO_USER ./*
+chown -R $SUDO_USER:$SUDO_USER ./*
+
+echo
+echo Next step: run sudo ./clean-setup
+echo '('I would do it for you, but you may not want me to.')'
+echo
 
 exit 0
 
diff --git a/sbin/make-seed-file b/sbin/make-seed-file
--- a/sbin/make-seed-file
+++ b/sbin/make-seed-file
@@ -32,11 +32,11 @@ if ! $(cp -r "$ADMIN_HOME_DIR/.ssh" "$TEMP_DIR/"); then
 	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
 	f_die "Failed copying ~/.ssh directory" false $?;
 	fi
-echo "Copying /var/local/git/go/install/clean-setup and /var/local/git/go/install/variables"
-if ! $(cp "/var/local/git/go/install/clean-setup" "/var/local/git/go/install/variables" "$TEMP_DIR/"); then
-	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
-	f_die "Failed copying /var/local/git/go/install files" false $?;
-	fi
+# echo "Copying /var/local/git/go/install/clean-setup and /var/local/git/go/install/variables"
+# if ! $(cp "/var/local/git/go/install/clean-setup" "/var/local/git/go/install/variables" "$TEMP_DIR/"); then
+# 	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
+# 	f_die "Failed copying /var/local/git/go/install files" false $?;
+# 	fi
 echo "Setting ownership for contents of '$TEMP_DIR'"
 if ! $(chown -R $ADMIN_USER:$ADMIN_USER "$TEMP_DIR"); then
 	if ! $(rm -r "$TEMP_DIR"); then f_die "Failed removing directory '$TEMP_DIR'" false $?; fi
